// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"github.com/gorundebug/servicelib/runtime"

	cron "github.com/gorundebug/analyticsservice/internal/functions/cron"
	endpoint "github.com/gorundebug/analyticsservice/internal/functions/endpoint"
	types "github.com/gorundebug/analyticsservice/internal/types"
	types2 "github.com/gorundebug/model_go/pkg/types"
)

type serviceHandlers struct {
}

type serviceEndpoints struct {
	handlers serviceHandlers

	analyticsSchedule       runtime.Consumer[string]
	orderProcessed          runtime.Consumer[*types2.OrderProcessed]
	analyticsOrders         runtime.Consumer[*types.AnalyticsEvent]
	analyticsPayments       runtime.Consumer[*types.AnalyticsEvent]
	analyticsShipments      runtime.Consumer[*types.AnalyticsEvent]
	cycleAnalyticsInput     runtime.Consumer[*types.AnalyticsEvent]
	substreamAnalyticsInput runtime.Consumer[*types.AnalyticsEvent]

	writeCycleAnalyticsCycleAnalyticsResult         runtime.Consumer[*types.AnalyticsEvent]
	writeJoinedAnalyticsJoinedAnalytics             runtime.Consumer[*types.AnalyticsResult]
	writeHighValueAnalyticsHighValueAnalytics       runtime.Consumer[*types.AnalyticsResult]
	writeStandardAnalyticsStandardAnalytics         runtime.Consumer[*types.AnalyticsResult]
	writeSubstreamAnalyticsSubstreamAnalyticsResult runtime.Consumer[*types.AnalyticsResult]
}

func (endpoints *serviceEndpoints) initEndpoints(s *Service) error {
	var err error

	if endpoints.analyticsSchedule, err = cron.MakeEndpointConsumerAnalyticsScheduleSource(s.streams.analyticsSchedule, s.functions.cronAnalyticsScheduleSource); err != nil {
		return err
	}
	if endpoints.orderProcessed, err = endpoint.MakeEndpointConsumerOrderProcessedEndpointSource(s.streams.consumeOrderProcessed, s.functions.endpointOrderProcessedEndpointSource); err != nil {
		return err
	}
	if endpoints.analyticsOrders, err = endpoint.MakeEndpointConsumerAnalyticsOrdersSource(s.streams.analyticsOrders, s.functions.endpointAnalyticsOrdersSource); err != nil {
		return err
	}
	if endpoints.analyticsPayments, err = endpoint.MakeEndpointConsumerAnalyticsPaymentsSource(s.streams.analyticsPayments, s.functions.endpointAnalyticsPaymentsSource); err != nil {
		return err
	}
	if endpoints.analyticsShipments, err = endpoint.MakeEndpointConsumerAnalyticsShipmentsSource(s.streams.analyticsShipments, s.functions.endpointAnalyticsShipmentsSource); err != nil {
		return err
	}
	if endpoints.cycleAnalyticsInput, err = endpoint.MakeEndpointConsumerCycleAnalyticsInputSource(s.streams.cycleAnalyticsInput, s.functions.endpointCycleAnalyticsInputSource); err != nil {
		return err
	}
	if endpoints.substreamAnalyticsInput, err = endpoint.MakeEndpointConsumerSubstreamAnalyticsInputSource(s.streams.substreamAnalyticsInput, s.functions.endpointSubstreamAnalyticsInputSource); err != nil {
		return err
	}

	if endpoints.writeCycleAnalyticsCycleAnalyticsResult, err = endpoint.MakeEndpointConsumerCycleAnalyticsResultSink(s.streams.writeCycleAnalytics, s.functions.endpointCycleAnalyticsResultSink); err != nil {
		return err
	}
	if endpoints.writeJoinedAnalyticsJoinedAnalytics, err = endpoint.MakeEndpointConsumerJoinedAnalyticsSink(s.streams.writeJoinedAnalytics, s.functions.endpointJoinedAnalyticsSink); err != nil {
		return err
	}
	if endpoints.writeHighValueAnalyticsHighValueAnalytics, err = endpoint.MakeEndpointConsumerHighValueAnalyticsSink(s.streams.writeHighValueAnalytics, s.functions.endpointHighValueAnalyticsSink); err != nil {
		return err
	}
	if endpoints.writeStandardAnalyticsStandardAnalytics, err = endpoint.MakeEndpointConsumerStandardAnalyticsSink(s.streams.writeStandardAnalytics, s.functions.endpointStandardAnalyticsSink); err != nil {
		return err
	}
	if endpoints.writeSubstreamAnalyticsSubstreamAnalyticsResult, err = endpoint.MakeEndpointConsumerSubstreamAnalyticsResultSink(s.streams.writeSubstreamAnalytics, s.functions.endpointSubstreamAnalyticsResultSink); err != nil {
		return err
	}
	return err
}
