// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"github.com/gorundebug/servicelib/runtime"
	"golang.org/x/sync/errgroup"

	analytics "github.com/gorundebug/analyticsservice/internal/functions/analytics"
	cron "github.com/gorundebug/analyticsservice/internal/functions/cron"
	cycleanalytics "github.com/gorundebug/analyticsservice/internal/functions/cycleanalytics"
	endpoint "github.com/gorundebug/analyticsservice/internal/functions/endpoint"
	joinanalytics "github.com/gorundebug/analyticsservice/internal/functions/joinanalytics"
	multijoinanalytics "github.com/gorundebug/analyticsservice/internal/functions/multijoinanalytics"
	substreamanalytics "github.com/gorundebug/analyticsservice/internal/functions/substreamanalytics"
)

type serviceFunctions struct {
	analyticsCountOrderProcessed                    *analytics.CountOrderProcessed
	joinanalyticsKeyOrdersForJoin                   *joinanalytics.KeyOrdersForJoin
	multijoinanalyticsKeyOrdersForMultiJoin         *multijoinanalytics.KeyOrdersForMultiJoin
	joinanalyticsKeyPaymentsForJoin                 *joinanalytics.KeyPaymentsForJoin
	joinanalyticsJoinOrderPaymentAnalytics          *joinanalytics.JoinOrderPaymentAnalytics
	multijoinanalyticsKeyPaymentsForMultiJoin       *multijoinanalytics.KeyPaymentsForMultiJoin
	multijoinanalyticsKeyShipmentsForMultiJoin      *multijoinanalytics.KeyShipmentsForMultiJoin
	multijoinanalyticsMultiJoinAnalyticsEvents      *multijoinanalytics.MultiJoinAnalyticsEvents
	multijoinanalyticsRouteAnalyticsResult          *multijoinanalytics.RouteAnalyticsResult
	cycleanalyticsAdvanceCycleAnalytics             *cycleanalytics.AdvanceCycleAnalytics
	cycleanalyticsCompleteCycleAnalytics            *cycleanalytics.CompleteCycleAnalytics
	cycleanalyticsContinueCycleAnalytics            *cycleanalytics.ContinueCycleAnalytics
	substreamanalyticsBuildSubstreamAnalyticsResult *substreamanalytics.BuildSubstreamAnalyticsResult
	substreamanalyticsInvokeAnalyticsSubstream      *substreamanalytics.InvokeAnalyticsSubstream

	cronAnalyticsScheduleSource           *cron.AnalyticsScheduleSource
	endpointOrderProcessedEndpointSource  *endpoint.OrderProcessedEndpointSource
	endpointAnalyticsOrdersSource         *endpoint.AnalyticsOrdersSource
	endpointAnalyticsPaymentsSource       *endpoint.AnalyticsPaymentsSource
	endpointAnalyticsShipmentsSource      *endpoint.AnalyticsShipmentsSource
	endpointCycleAnalyticsInputSource     *endpoint.CycleAnalyticsInputSource
	endpointSubstreamAnalyticsInputSource *endpoint.SubstreamAnalyticsInputSource

	endpointCycleAnalyticsResultSink     *endpoint.CycleAnalyticsResultSink
	endpointJoinedAnalyticsSink          *endpoint.JoinedAnalyticsSink
	endpointHighValueAnalyticsSink       *endpoint.HighValueAnalyticsSink
	endpointStandardAnalyticsSink        *endpoint.StandardAnalyticsSink
	endpointSubstreamAnalyticsResultSink *endpoint.SubstreamAnalyticsResultSink
}

type makerTaskGroup interface{ Go(func() error) }

func (functions *serviceFunctions) initFunctions(ctx context.Context, env runtime.RuntimeEnvironment, makers *serviceMakers) error {

	eg, egCtx := errgroup.WithContext(ctx)
	functions.scheduleFunctions(eg, egCtx, env, makers)
	if err := eg.Wait(); err != nil {
		return err
	}

	return nil
}

func (functions *serviceFunctions) scheduleFunctions(tasks makerTaskGroup, ctx context.Context, env runtime.RuntimeEnvironment, makers *serviceMakers) {

	eg := tasks
	egCtx := ctx

	if makers.analyticsCountOrderProcessedMaker != nil {
		eg.Go(func() error {
			var err error
			functions.analyticsCountOrderProcessed, err = makers.analyticsCountOrderProcessedMaker(egCtx, env)
			return err
		})
	}
	if makers.joinanalyticsKeyOrdersForJoinMaker != nil {
		eg.Go(func() error {
			var err error
			functions.joinanalyticsKeyOrdersForJoin, err = makers.joinanalyticsKeyOrdersForJoinMaker(egCtx, env)
			return err
		})
	}
	if makers.multijoinanalyticsKeyOrdersForMultiJoinMaker != nil {
		eg.Go(func() error {
			var err error
			functions.multijoinanalyticsKeyOrdersForMultiJoin, err = makers.multijoinanalyticsKeyOrdersForMultiJoinMaker(egCtx, env)
			return err
		})
	}
	if makers.joinanalyticsKeyPaymentsForJoinMaker != nil {
		eg.Go(func() error {
			var err error
			functions.joinanalyticsKeyPaymentsForJoin, err = makers.joinanalyticsKeyPaymentsForJoinMaker(egCtx, env)
			return err
		})
	}
	if makers.joinanalyticsJoinOrderPaymentAnalyticsMaker != nil {
		eg.Go(func() error {
			var err error
			functions.joinanalyticsJoinOrderPaymentAnalytics, err = makers.joinanalyticsJoinOrderPaymentAnalyticsMaker(egCtx, env)
			return err
		})
	}
	if makers.multijoinanalyticsKeyPaymentsForMultiJoinMaker != nil {
		eg.Go(func() error {
			var err error
			functions.multijoinanalyticsKeyPaymentsForMultiJoin, err = makers.multijoinanalyticsKeyPaymentsForMultiJoinMaker(egCtx, env)
			return err
		})
	}
	if makers.multijoinanalyticsKeyShipmentsForMultiJoinMaker != nil {
		eg.Go(func() error {
			var err error
			functions.multijoinanalyticsKeyShipmentsForMultiJoin, err = makers.multijoinanalyticsKeyShipmentsForMultiJoinMaker(egCtx, env)
			return err
		})
	}
	if makers.multijoinanalyticsMultiJoinAnalyticsEventsMaker != nil {
		eg.Go(func() error {
			var err error
			functions.multijoinanalyticsMultiJoinAnalyticsEvents, err = makers.multijoinanalyticsMultiJoinAnalyticsEventsMaker(egCtx, env)
			return err
		})
	}
	if makers.multijoinanalyticsRouteAnalyticsResultMaker != nil {
		eg.Go(func() error {
			var err error
			functions.multijoinanalyticsRouteAnalyticsResult, err = makers.multijoinanalyticsRouteAnalyticsResultMaker(egCtx, env)
			return err
		})
	}
	if makers.cycleanalyticsAdvanceCycleAnalyticsMaker != nil {
		eg.Go(func() error {
			var err error
			functions.cycleanalyticsAdvanceCycleAnalytics, err = makers.cycleanalyticsAdvanceCycleAnalyticsMaker(egCtx, env)
			return err
		})
	}
	if makers.cycleanalyticsCompleteCycleAnalyticsMaker != nil {
		eg.Go(func() error {
			var err error
			functions.cycleanalyticsCompleteCycleAnalytics, err = makers.cycleanalyticsCompleteCycleAnalyticsMaker(egCtx, env)
			return err
		})
	}
	if makers.cycleanalyticsContinueCycleAnalyticsMaker != nil {
		eg.Go(func() error {
			var err error
			functions.cycleanalyticsContinueCycleAnalytics, err = makers.cycleanalyticsContinueCycleAnalyticsMaker(egCtx, env)
			return err
		})
	}
	if makers.substreamanalyticsBuildSubstreamAnalyticsResultMaker != nil {
		eg.Go(func() error {
			var err error
			functions.substreamanalyticsBuildSubstreamAnalyticsResult, err = makers.substreamanalyticsBuildSubstreamAnalyticsResultMaker(egCtx, env)
			return err
		})
	}
	if makers.substreamanalyticsInvokeAnalyticsSubstreamMaker != nil {
		eg.Go(func() error {
			var err error
			functions.substreamanalyticsInvokeAnalyticsSubstream, err = makers.substreamanalyticsInvokeAnalyticsSubstreamMaker(egCtx, env)
			return err
		})
	}

	if makers.cronAnalyticsScheduleSourceMaker != nil {
		eg.Go(func() error {
			var err error
			functions.cronAnalyticsScheduleSource, err = makers.cronAnalyticsScheduleSourceMaker(egCtx, env)
			return err
		})
	}
	if makers.endpointOrderProcessedEndpointSourceMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointOrderProcessedEndpointSource, err = makers.endpointOrderProcessedEndpointSourceMaker(egCtx, env)
			return err
		})
	}
	if makers.endpointAnalyticsOrdersSourceMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointAnalyticsOrdersSource, err = makers.endpointAnalyticsOrdersSourceMaker(egCtx, env)
			return err
		})
	}
	if makers.endpointAnalyticsPaymentsSourceMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointAnalyticsPaymentsSource, err = makers.endpointAnalyticsPaymentsSourceMaker(egCtx, env)
			return err
		})
	}
	if makers.endpointAnalyticsShipmentsSourceMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointAnalyticsShipmentsSource, err = makers.endpointAnalyticsShipmentsSourceMaker(egCtx, env)
			return err
		})
	}
	if makers.endpointCycleAnalyticsInputSourceMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointCycleAnalyticsInputSource, err = makers.endpointCycleAnalyticsInputSourceMaker(egCtx, env)
			return err
		})
	}
	if makers.endpointSubstreamAnalyticsInputSourceMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointSubstreamAnalyticsInputSource, err = makers.endpointSubstreamAnalyticsInputSourceMaker(egCtx, env)
			return err
		})
	}

	if makers.endpointCycleAnalyticsResultSinkMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointCycleAnalyticsResultSink, err = makers.endpointCycleAnalyticsResultSinkMaker(egCtx, env)
			return err
		})
	}
	if makers.endpointJoinedAnalyticsSinkMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointJoinedAnalyticsSink, err = makers.endpointJoinedAnalyticsSinkMaker(egCtx, env)
			return err
		})
	}
	if makers.endpointHighValueAnalyticsSinkMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointHighValueAnalyticsSink, err = makers.endpointHighValueAnalyticsSinkMaker(egCtx, env)
			return err
		})
	}
	if makers.endpointStandardAnalyticsSinkMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointStandardAnalyticsSink, err = makers.endpointStandardAnalyticsSinkMaker(egCtx, env)
			return err
		})
	}
	if makers.endpointSubstreamAnalyticsResultSinkMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointSubstreamAnalyticsResultSink, err = makers.endpointSubstreamAnalyticsResultSinkMaker(egCtx, env)
			return err
		})
	}
}
