// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"github.com/gorundebug/servicelib/runtime"
	"github.com/gorundebug/servicelib/runtime/environment"
	"net/http"

	analytics "github.com/gorundebug/analyticsservice/internal/functions/analytics"
	cron "github.com/gorundebug/analyticsservice/internal/functions/cron"
	cycleanalytics "github.com/gorundebug/analyticsservice/internal/functions/cycleanalytics"
	endpoint "github.com/gorundebug/analyticsservice/internal/functions/endpoint"
	joinanalytics "github.com/gorundebug/analyticsservice/internal/functions/joinanalytics"
	multijoinanalytics "github.com/gorundebug/analyticsservice/internal/functions/multijoinanalytics"
	substreamanalytics "github.com/gorundebug/analyticsservice/internal/functions/substreamanalytics"
)

type serviceMakers struct {
	httpServerMaker func(context.Context, runtime.RuntimeEnvironment) (*http.Server, error)
	httpMuxMaker    func(context.Context, runtime.RuntimeEnvironment) (*http.ServeMux, error)

	analyticsCountOrderProcessedMaker                    func(ctx context.Context, env environment.ServiceEnvironment) (*analytics.CountOrderProcessed, error)
	joinanalyticsKeyOrdersForJoinMaker                   func(ctx context.Context, env environment.ServiceEnvironment) (*joinanalytics.KeyOrdersForJoin, error)
	multijoinanalyticsKeyOrdersForMultiJoinMaker         func(ctx context.Context, env environment.ServiceEnvironment) (*multijoinanalytics.KeyOrdersForMultiJoin, error)
	joinanalyticsKeyPaymentsForJoinMaker                 func(ctx context.Context, env environment.ServiceEnvironment) (*joinanalytics.KeyPaymentsForJoin, error)
	joinanalyticsJoinOrderPaymentAnalyticsMaker          func(ctx context.Context, env environment.ServiceEnvironment) (*joinanalytics.JoinOrderPaymentAnalytics, error)
	multijoinanalyticsKeyPaymentsForMultiJoinMaker       func(ctx context.Context, env environment.ServiceEnvironment) (*multijoinanalytics.KeyPaymentsForMultiJoin, error)
	multijoinanalyticsKeyShipmentsForMultiJoinMaker      func(ctx context.Context, env environment.ServiceEnvironment) (*multijoinanalytics.KeyShipmentsForMultiJoin, error)
	multijoinanalyticsMultiJoinAnalyticsEventsMaker      func(ctx context.Context, env environment.ServiceEnvironment) (*multijoinanalytics.MultiJoinAnalyticsEvents, error)
	multijoinanalyticsRouteAnalyticsResultMaker          func(ctx context.Context, env environment.ServiceEnvironment) (*multijoinanalytics.RouteAnalyticsResult, error)
	cycleanalyticsAdvanceCycleAnalyticsMaker             func(ctx context.Context, env environment.ServiceEnvironment) (*cycleanalytics.AdvanceCycleAnalytics, error)
	cycleanalyticsCompleteCycleAnalyticsMaker            func(ctx context.Context, env environment.ServiceEnvironment) (*cycleanalytics.CompleteCycleAnalytics, error)
	cycleanalyticsContinueCycleAnalyticsMaker            func(ctx context.Context, env environment.ServiceEnvironment) (*cycleanalytics.ContinueCycleAnalytics, error)
	substreamanalyticsBuildSubstreamAnalyticsResultMaker func(ctx context.Context, env environment.ServiceEnvironment) (*substreamanalytics.BuildSubstreamAnalyticsResult, error)
	substreamanalyticsInvokeAnalyticsSubstreamMaker      func(ctx context.Context, env environment.ServiceEnvironment) (*substreamanalytics.InvokeAnalyticsSubstream, error)

	cronAnalyticsScheduleSourceMaker           func(ctx context.Context, env environment.ServiceEnvironment) (*cron.AnalyticsScheduleSource, error)
	endpointOrderProcessedEndpointSourceMaker  func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.OrderProcessedEndpointSource, error)
	endpointAnalyticsOrdersSourceMaker         func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.AnalyticsOrdersSource, error)
	endpointAnalyticsPaymentsSourceMaker       func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.AnalyticsPaymentsSource, error)
	endpointAnalyticsShipmentsSourceMaker      func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.AnalyticsShipmentsSource, error)
	endpointCycleAnalyticsInputSourceMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.CycleAnalyticsInputSource, error)
	endpointSubstreamAnalyticsInputSourceMaker func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.SubstreamAnalyticsInputSource, error)

	endpointCycleAnalyticsResultSinkMaker     func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.CycleAnalyticsResultSink, error)
	endpointJoinedAnalyticsSinkMaker          func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.JoinedAnalyticsSink, error)
	endpointHighValueAnalyticsSinkMaker       func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.HighValueAnalyticsSink, error)
	endpointStandardAnalyticsSinkMaker        func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.StandardAnalyticsSink, error)
	endpointSubstreamAnalyticsResultSinkMaker func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.SubstreamAnalyticsResultSink, error)
}

func (makers *serviceMakers) initMakers(ctx context.Context) error {

	if makers.analyticsCountOrderProcessedMaker == nil {
		makers.analyticsCountOrderProcessedMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*analytics.CountOrderProcessed, error) {
			return analytics.MakeCountOrderProcessed(ctx, env)
		}
	}
	if makers.joinanalyticsKeyOrdersForJoinMaker == nil {
		makers.joinanalyticsKeyOrdersForJoinMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*joinanalytics.KeyOrdersForJoin, error) {
			return joinanalytics.MakeKeyOrdersForJoin(ctx, env)
		}
	}
	if makers.multijoinanalyticsKeyOrdersForMultiJoinMaker == nil {
		makers.multijoinanalyticsKeyOrdersForMultiJoinMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*multijoinanalytics.KeyOrdersForMultiJoin, error) {
			return multijoinanalytics.MakeKeyOrdersForMultiJoin(ctx, env)
		}
	}
	if makers.joinanalyticsKeyPaymentsForJoinMaker == nil {
		makers.joinanalyticsKeyPaymentsForJoinMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*joinanalytics.KeyPaymentsForJoin, error) {
			return joinanalytics.MakeKeyPaymentsForJoin(ctx, env)
		}
	}
	if makers.joinanalyticsJoinOrderPaymentAnalyticsMaker == nil {
		makers.joinanalyticsJoinOrderPaymentAnalyticsMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*joinanalytics.JoinOrderPaymentAnalytics, error) {
			return joinanalytics.MakeJoinOrderPaymentAnalytics(ctx, env)
		}
	}
	if makers.multijoinanalyticsKeyPaymentsForMultiJoinMaker == nil {
		makers.multijoinanalyticsKeyPaymentsForMultiJoinMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*multijoinanalytics.KeyPaymentsForMultiJoin, error) {
			return multijoinanalytics.MakeKeyPaymentsForMultiJoin(ctx, env)
		}
	}
	if makers.multijoinanalyticsKeyShipmentsForMultiJoinMaker == nil {
		makers.multijoinanalyticsKeyShipmentsForMultiJoinMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*multijoinanalytics.KeyShipmentsForMultiJoin, error) {
			return multijoinanalytics.MakeKeyShipmentsForMultiJoin(ctx, env)
		}
	}
	if makers.multijoinanalyticsMultiJoinAnalyticsEventsMaker == nil {
		makers.multijoinanalyticsMultiJoinAnalyticsEventsMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*multijoinanalytics.MultiJoinAnalyticsEvents, error) {
			return multijoinanalytics.MakeMultiJoinAnalyticsEvents(ctx, env)
		}
	}
	if makers.multijoinanalyticsRouteAnalyticsResultMaker == nil {
		makers.multijoinanalyticsRouteAnalyticsResultMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*multijoinanalytics.RouteAnalyticsResult, error) {
			return multijoinanalytics.MakeRouteAnalyticsResult(ctx, env)
		}
	}
	if makers.cycleanalyticsAdvanceCycleAnalyticsMaker == nil {
		makers.cycleanalyticsAdvanceCycleAnalyticsMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*cycleanalytics.AdvanceCycleAnalytics, error) {
			return cycleanalytics.MakeAdvanceCycleAnalytics(ctx, env)
		}
	}
	if makers.cycleanalyticsCompleteCycleAnalyticsMaker == nil {
		makers.cycleanalyticsCompleteCycleAnalyticsMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*cycleanalytics.CompleteCycleAnalytics, error) {
			return cycleanalytics.MakeCompleteCycleAnalytics(ctx, env)
		}
	}
	if makers.cycleanalyticsContinueCycleAnalyticsMaker == nil {
		makers.cycleanalyticsContinueCycleAnalyticsMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*cycleanalytics.ContinueCycleAnalytics, error) {
			return cycleanalytics.MakeContinueCycleAnalytics(ctx, env)
		}
	}
	if makers.substreamanalyticsBuildSubstreamAnalyticsResultMaker == nil {
		makers.substreamanalyticsBuildSubstreamAnalyticsResultMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*substreamanalytics.BuildSubstreamAnalyticsResult, error) {
			return substreamanalytics.MakeBuildSubstreamAnalyticsResult(ctx, env)
		}
	}
	if makers.substreamanalyticsInvokeAnalyticsSubstreamMaker == nil {
		makers.substreamanalyticsInvokeAnalyticsSubstreamMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*substreamanalytics.InvokeAnalyticsSubstream, error) {
			return substreamanalytics.MakeInvokeAnalyticsSubstream(ctx, env)
		}
	}

	if makers.cronAnalyticsScheduleSourceMaker == nil {
		makers.cronAnalyticsScheduleSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*cron.AnalyticsScheduleSource, error) {
			return cron.MakeAnalyticsScheduleSource(ctx, env)
		}
	}
	if makers.endpointOrderProcessedEndpointSourceMaker == nil {
		makers.endpointOrderProcessedEndpointSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.OrderProcessedEndpointSource, error) {
			return endpoint.MakeOrderProcessedEndpointSource(ctx, env)
		}
	}
	if makers.endpointAnalyticsOrdersSourceMaker == nil {
		makers.endpointAnalyticsOrdersSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.AnalyticsOrdersSource, error) {
			return endpoint.MakeAnalyticsOrdersSource(ctx, env)
		}
	}
	if makers.endpointAnalyticsPaymentsSourceMaker == nil {
		makers.endpointAnalyticsPaymentsSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.AnalyticsPaymentsSource, error) {
			return endpoint.MakeAnalyticsPaymentsSource(ctx, env)
		}
	}
	if makers.endpointAnalyticsShipmentsSourceMaker == nil {
		makers.endpointAnalyticsShipmentsSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.AnalyticsShipmentsSource, error) {
			return endpoint.MakeAnalyticsShipmentsSource(ctx, env)
		}
	}
	if makers.endpointCycleAnalyticsInputSourceMaker == nil {
		makers.endpointCycleAnalyticsInputSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.CycleAnalyticsInputSource, error) {
			return endpoint.MakeCycleAnalyticsInputSource(ctx, env)
		}
	}
	if makers.endpointSubstreamAnalyticsInputSourceMaker == nil {
		makers.endpointSubstreamAnalyticsInputSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.SubstreamAnalyticsInputSource, error) {
			return endpoint.MakeSubstreamAnalyticsInputSource(ctx, env)
		}
	}

	if makers.endpointCycleAnalyticsResultSinkMaker == nil {
		makers.endpointCycleAnalyticsResultSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.CycleAnalyticsResultSink, error) {
			return endpoint.MakeCycleAnalyticsResultSink(ctx, env)
		}
	}
	if makers.endpointJoinedAnalyticsSinkMaker == nil {
		makers.endpointJoinedAnalyticsSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.JoinedAnalyticsSink, error) {
			return endpoint.MakeJoinedAnalyticsSink(ctx, env)
		}
	}
	if makers.endpointHighValueAnalyticsSinkMaker == nil {
		makers.endpointHighValueAnalyticsSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.HighValueAnalyticsSink, error) {
			return endpoint.MakeHighValueAnalyticsSink(ctx, env)
		}
	}
	if makers.endpointStandardAnalyticsSinkMaker == nil {
		makers.endpointStandardAnalyticsSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.StandardAnalyticsSink, error) {
			return endpoint.MakeStandardAnalyticsSink(ctx, env)
		}
	}
	if makers.endpointSubstreamAnalyticsResultSinkMaker == nil {
		makers.endpointSubstreamAnalyticsResultSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.SubstreamAnalyticsResultSink, error) {
			return endpoint.MakeSubstreamAnalyticsResultSink(ctx, env)
		}
	}

	return nil
}
