// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"

	"github.com/gorundebug/analyticsservice/internal/config"
	"github.com/gorundebug/analyticsservice/internal/functions/endpoint"
	"github.com/gorundebug/analyticsservice/internal/functions/joinanalytics"
	"github.com/gorundebug/analyticsservice/internal/types"
	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/datastruct"
	"github.com/gorundebug/servicelib/runtime/environment"
	"github.com/gorundebug/servicelib/transformation"
)

type joinAnalyticsPipelineMakers struct {
	// stream function makers
	joinanalyticsKeyOrdersForJoinMaker          func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*joinanalytics.KeyOrdersForJoin, error)
	joinanalyticsKeyPaymentsForJoinMaker        func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*joinanalytics.KeyPaymentsForJoin, error)
	joinanalyticsJoinOrderPaymentAnalyticsMaker func(ctx context.Context, cfg *runtimecfg.JoinStreamConfig, env environment.ServiceEnvironment) (*joinanalytics.JoinOrderPaymentAnalytics, error)
	// data source function makers
	// data sink function makers
	endpointJoinedAnalyticsSinkMaker func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.JoinedAnalyticsSink, error)
}

type joinAnalyticsPipelineFunctions struct {
	// stream functions
	joinanalyticsKeyOrdersForJoin          *joinanalytics.KeyOrdersForJoin
	joinanalyticsKeyPaymentsForJoin        *joinanalytics.KeyPaymentsForJoin
	joinanalyticsJoinOrderPaymentAnalytics *joinanalytics.JoinOrderPaymentAnalytics
	// data source functions
	// data sink functions
	endpointJoinedAnalyticsSink *endpoint.JoinedAnalyticsSink
}

type joinAnalyticsPipelineStreams struct {
	keyOrdersForJoin          runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, datastruct.KeyValue[string, *types.AnalyticsEvent]]
	keyPaymentsForJoin        runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, datastruct.KeyValue[string, *types.AnalyticsEvent]]
	joinOrderPaymentAnalytics runtime.TypedJoinConsumedStream[string, *types.AnalyticsEvent, *types.AnalyticsEvent, *types.AnalyticsResult]
	writeJoinedAnalytics      runtime.TypedSinkStream[*types.AnalyticsResult, error]
}

type joinAnalyticsPipelineHandlers struct {
	// data source handlers
}

type joinAnalyticsPipelineDataConnectors struct {
	// data sources
	// data sinks
	writeJoinedAnalyticsJoinedAnalytics runtime.Consumer[*types.AnalyticsResult]
}

func (s *Service) initJoinAnalyticsMakers() {
	if s.makers.joinanalyticsKeyOrdersForJoinMaker == nil {
		s.makers.joinanalyticsKeyOrdersForJoinMaker = func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*joinanalytics.KeyOrdersForJoin, error) {
			return joinanalytics.MakeKeyOrdersForJoin(ctx, env, cfg)
		}
	}
	if s.makers.joinanalyticsKeyPaymentsForJoinMaker == nil {
		s.makers.joinanalyticsKeyPaymentsForJoinMaker = func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*joinanalytics.KeyPaymentsForJoin, error) {
			return joinanalytics.MakeKeyPaymentsForJoin(ctx, env, cfg)
		}
	}
	if s.makers.joinanalyticsJoinOrderPaymentAnalyticsMaker == nil {
		s.makers.joinanalyticsJoinOrderPaymentAnalyticsMaker = func(ctx context.Context, cfg *runtimecfg.JoinStreamConfig, env environment.ServiceEnvironment) (*joinanalytics.JoinOrderPaymentAnalytics, error) {
			return joinanalytics.MakeJoinOrderPaymentAnalytics(ctx, env, cfg)
		}
	}
	if s.makers.endpointJoinedAnalyticsSinkMaker == nil {
		s.makers.endpointJoinedAnalyticsSinkMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.JoinedAnalyticsSink, error) {
			return endpoint.MakeJoinedAnalyticsSink(ctx, env, cfg)
		}
	}
}

// initJoinAnalyticsStreams constructs the streams owned by this
// pipeline. The service-level coordinator preserves the global construction,
// binding and post-initialization phases across all pipelines.
func (s *Service) initJoinAnalyticsStreams(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx
	_ = cfg
	_ = env
	if err = s.initJoinAnalyticsKeyOrdersForJoinStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initJoinAnalyticsKeyPaymentsForJoinStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initJoinAnalyticsJoinOrderPaymentAnalyticsStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initJoinAnalyticsWriteJoinedAnalyticsStream(ctx, cfg, env); err != nil {
		return err
	}
	return nil
}

func (s *Service) bindJoinAnalyticsStreams() error {
	return nil
}

func (s *Service) initJoinAnalyticsEndpoints() error {
	var err error
	if s.dataConnectors.writeJoinedAnalyticsJoinedAnalytics, err = endpoint.MakeEndpointConsumerJoinedAnalyticsSink(s.streams.writeJoinedAnalytics, s.functions.endpointJoinedAnalyticsSink); err != nil {
		return err
	}
	_ = err
	return nil
}

func (s *Service) postInitJoinAnalyticsStreams() error {
	return nil
}
func (s *Service) initJoinAnalyticsKeyOrdersForJoinStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.keyOrdersForJoin, err = transformation.KeyBy[*types.AnalyticsEvent, string, *types.AnalyticsEvent](&cfg.Streams.KeyOrdersForJoin, s.streams.splitAnalyticsOrders.AddStream(), s.functions.joinanalyticsKeyOrdersForJoin); err != nil {
		return err
	}
	return nil
}
func (s *Service) initJoinAnalyticsKeyPaymentsForJoinStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.keyPaymentsForJoin, err = transformation.KeyBy[*types.AnalyticsEvent, string, *types.AnalyticsEvent](&cfg.Streams.KeyPaymentsForJoin, s.streams.splitAnalyticsPayments.AddStream(), s.functions.joinanalyticsKeyPaymentsForJoin); err != nil {
		return err
	}
	return nil
}
func (s *Service) initJoinAnalyticsJoinOrderPaymentAnalyticsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.joinOrderPaymentAnalytics, err = transformation.Join[string, *types.AnalyticsEvent, *types.AnalyticsEvent, *types.AnalyticsResult](&cfg.Streams.JoinOrderPaymentAnalytics, s.streams.keyOrdersForJoin, s.streams.keyPaymentsForJoin, s.functions.joinanalyticsJoinOrderPaymentAnalytics); err != nil {
		return err
	}
	return nil
}
func (s *Service) initJoinAnalyticsWriteJoinedAnalyticsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.writeJoinedAnalytics, err = transformation.Sink[*types.AnalyticsResult, error](&cfg.Streams.WriteJoinedAnalytics, s.streams.joinOrderPaymentAnalytics); err != nil {
		return err
	}
	return nil
}
func (s *Service) scheduleJoinAnalyticsFunctions(
	eg pipelineMakerTaskGroup,
	egCtx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) {
	if s.makers.joinanalyticsKeyOrdersForJoinMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.joinanalyticsKeyOrdersForJoin, err = s.makers.joinanalyticsKeyOrdersForJoinMaker(egCtx, &cfg.Streams.KeyOrdersForJoin, env)
			return err
		})
	}
	if s.makers.joinanalyticsKeyPaymentsForJoinMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.joinanalyticsKeyPaymentsForJoin, err = s.makers.joinanalyticsKeyPaymentsForJoinMaker(egCtx, &cfg.Streams.KeyPaymentsForJoin, env)
			return err
		})
	}
	if s.makers.joinanalyticsJoinOrderPaymentAnalyticsMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.joinanalyticsJoinOrderPaymentAnalytics, err = s.makers.joinanalyticsJoinOrderPaymentAnalyticsMaker(egCtx, &cfg.Streams.JoinOrderPaymentAnalytics, env)
			return err
		})
	}
	if s.makers.endpointJoinedAnalyticsSinkMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointJoinedAnalyticsSink, err = s.makers.endpointJoinedAnalyticsSinkMaker(egCtx, &cfg.Endpoints.JoinedAnalytics, env)
			return err
		})
	}
}
