// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"

	"github.com/gorundebug/analyticsservice/internal/config"
	"github.com/gorundebug/analyticsservice/internal/functions/endpoint"
	"github.com/gorundebug/analyticsservice/internal/types"
	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/environment"
	"github.com/gorundebug/servicelib/transformation"
)

type analyticsSourcesPipelineMakers struct {
	// stream function makers
	// data source function makers
	endpointAnalyticsOrdersSourceMaker    func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.AnalyticsOrdersSource, error)
	endpointAnalyticsPaymentsSourceMaker  func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.AnalyticsPaymentsSource, error)
	endpointAnalyticsShipmentsSourceMaker func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.AnalyticsShipmentsSource, error)
	// data sink function makers
}

type analyticsSourcesPipelineFunctions struct {
	// stream functions
	// data source functions
	endpointAnalyticsOrdersSource    *endpoint.AnalyticsOrdersSource
	endpointAnalyticsPaymentsSource  *endpoint.AnalyticsPaymentsSource
	endpointAnalyticsShipmentsSource *endpoint.AnalyticsShipmentsSource
	// data sink functions
}

type analyticsSourcesPipelineStreams struct {
	analyticsOrders        runtime.TypedInputStream[*types.AnalyticsEvent, any, error]
	splitAnalyticsOrders   runtime.TypedSplitStream[*types.AnalyticsEvent]
	analyticsPayments      runtime.TypedInputStream[*types.AnalyticsEvent, any, error]
	splitAnalyticsPayments runtime.TypedSplitStream[*types.AnalyticsEvent]
	analyticsShipments     runtime.TypedInputStream[*types.AnalyticsEvent, any, error]
}

type analyticsSourcesPipelineHandlers struct {
	// data source handlers
}

type analyticsSourcesPipelineDataConnectors struct {
	// data sources
	analyticsOrders    runtime.Consumer[*types.AnalyticsEvent]
	analyticsPayments  runtime.Consumer[*types.AnalyticsEvent]
	analyticsShipments runtime.Consumer[*types.AnalyticsEvent]
	// data sinks
}

func (s *Service) initAnalyticsSourcesMakers() {
	if s.makers.endpointAnalyticsOrdersSourceMaker == nil {
		s.makers.endpointAnalyticsOrdersSourceMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.AnalyticsOrdersSource, error) {
			return endpoint.MakeAnalyticsOrdersSource(ctx, env, cfg)
		}
	}
	if s.makers.endpointAnalyticsPaymentsSourceMaker == nil {
		s.makers.endpointAnalyticsPaymentsSourceMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.AnalyticsPaymentsSource, error) {
			return endpoint.MakeAnalyticsPaymentsSource(ctx, env, cfg)
		}
	}
	if s.makers.endpointAnalyticsShipmentsSourceMaker == nil {
		s.makers.endpointAnalyticsShipmentsSourceMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.AnalyticsShipmentsSource, error) {
			return endpoint.MakeAnalyticsShipmentsSource(ctx, env, cfg)
		}
	}
}

// initAnalyticsSourcesStreams constructs the streams owned by this
// pipeline. The service-level coordinator preserves the global construction,
// binding and post-initialization phases across all pipelines.
func (s *Service) initAnalyticsSourcesStreams(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx
	_ = cfg
	_ = env
	if err = s.initAnalyticsSourcesAnalyticsOrdersStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initAnalyticsSourcesSplitAnalyticsOrdersStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initAnalyticsSourcesAnalyticsPaymentsStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initAnalyticsSourcesSplitAnalyticsPaymentsStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initAnalyticsSourcesAnalyticsShipmentsStream(ctx, cfg, env); err != nil {
		return err
	}
	return nil
}

func (s *Service) bindAnalyticsSourcesStreams() error {
	return nil
}

func (s *Service) initAnalyticsSourcesEndpoints() error {
	var err error
	if s.dataConnectors.analyticsOrders, err = endpoint.MakeEndpointConsumerAnalyticsOrdersSource(s.streams.analyticsOrders, s.functions.endpointAnalyticsOrdersSource); err != nil {
		return err
	}
	if s.dataConnectors.analyticsPayments, err = endpoint.MakeEndpointConsumerAnalyticsPaymentsSource(s.streams.analyticsPayments, s.functions.endpointAnalyticsPaymentsSource); err != nil {
		return err
	}
	if s.dataConnectors.analyticsShipments, err = endpoint.MakeEndpointConsumerAnalyticsShipmentsSource(s.streams.analyticsShipments, s.functions.endpointAnalyticsShipmentsSource); err != nil {
		return err
	}
	_ = err
	return nil
}

func (s *Service) postInitAnalyticsSourcesStreams() error {
	return nil
}
func (s *Service) initAnalyticsSourcesAnalyticsOrdersStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.analyticsOrders, err = transformation.Input[*types.AnalyticsEvent, any, error](&cfg.Streams.AnalyticsOrders, env); err != nil {
		return err
	}
	return nil
}
func (s *Service) initAnalyticsSourcesSplitAnalyticsOrdersStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.splitAnalyticsOrders, err = transformation.Split[*types.AnalyticsEvent](&cfg.Streams.SplitAnalyticsOrders, s.streams.analyticsOrders); err != nil {
		return err
	}
	return nil
}
func (s *Service) initAnalyticsSourcesAnalyticsPaymentsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.analyticsPayments, err = transformation.Input[*types.AnalyticsEvent, any, error](&cfg.Streams.AnalyticsPayments, env); err != nil {
		return err
	}
	return nil
}
func (s *Service) initAnalyticsSourcesSplitAnalyticsPaymentsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.splitAnalyticsPayments, err = transformation.Split[*types.AnalyticsEvent](&cfg.Streams.SplitAnalyticsPayments, s.streams.analyticsPayments); err != nil {
		return err
	}
	return nil
}
func (s *Service) initAnalyticsSourcesAnalyticsShipmentsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.analyticsShipments, err = transformation.Input[*types.AnalyticsEvent, any, error](&cfg.Streams.AnalyticsShipments, env); err != nil {
		return err
	}
	return nil
}
func (s *Service) scheduleAnalyticsSourcesFunctions(
	eg pipelineMakerTaskGroup,
	egCtx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) {
	if s.makers.endpointAnalyticsOrdersSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointAnalyticsOrdersSource, err = s.makers.endpointAnalyticsOrdersSourceMaker(egCtx, &cfg.Endpoints.AnalyticsOrders, env)
			return err
		})
	}
	if s.makers.endpointAnalyticsPaymentsSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointAnalyticsPaymentsSource, err = s.makers.endpointAnalyticsPaymentsSourceMaker(egCtx, &cfg.Endpoints.AnalyticsPayments, env)
			return err
		})
	}
	if s.makers.endpointAnalyticsShipmentsSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointAnalyticsShipmentsSource, err = s.makers.endpointAnalyticsShipmentsSourceMaker(egCtx, &cfg.Endpoints.AnalyticsShipments, env)
			return err
		})
	}
}
