// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"

	"github.com/gorundebug/analyticsservice/internal/config"
	"github.com/gorundebug/analyticsservice/internal/functions/cycleanalytics"
	"github.com/gorundebug/analyticsservice/internal/functions/endpoint"
	"github.com/gorundebug/analyticsservice/internal/types"
	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/environment"
	"github.com/gorundebug/servicelib/transformation"
)

type cycleAnalyticsPipelineMakers struct {
	// stream function makers
	cycleanalyticsAdvanceCycleAnalyticsMaker  func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*cycleanalytics.AdvanceCycleAnalytics, error)
	cycleanalyticsCompleteCycleAnalyticsMaker func(ctx context.Context, cfg *runtimecfg.FilterStreamConfig, env environment.ServiceEnvironment) (*cycleanalytics.CompleteCycleAnalytics, error)
	cycleanalyticsContinueCycleAnalyticsMaker func(ctx context.Context, cfg *runtimecfg.FilterStreamConfig, env environment.ServiceEnvironment) (*cycleanalytics.ContinueCycleAnalytics, error)
	// data source function makers
	endpointCycleAnalyticsInputSourceMaker func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.CycleAnalyticsInputSource, error)
	// data sink function makers
	endpointCycleAnalyticsResultSinkMaker func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.CycleAnalyticsResultSink, error)
}

type cycleAnalyticsPipelineFunctions struct {
	// stream functions
	cycleanalyticsAdvanceCycleAnalytics  *cycleanalytics.AdvanceCycleAnalytics
	cycleanalyticsCompleteCycleAnalytics *cycleanalytics.CompleteCycleAnalytics
	cycleanalyticsContinueCycleAnalytics *cycleanalytics.ContinueCycleAnalytics
	// data source functions
	endpointCycleAnalyticsInputSource *endpoint.CycleAnalyticsInputSource
	// data sink functions
	endpointCycleAnalyticsResultSink *endpoint.CycleAnalyticsResultSink
}

type cycleAnalyticsPipelineStreams struct {
	cycleAnalyticsLink     runtime.TypedLinkStream[*types.AnalyticsEvent]
	cycleAnalyticsInput    runtime.TypedInputStream[*types.AnalyticsEvent, any, error]
	mergeCycleAnalytics    runtime.TypedConsumedStream[*types.AnalyticsEvent]
	advanceCycleAnalytics  runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, *types.AnalyticsEvent]
	splitCycleAnalytics    runtime.TypedSplitStream[*types.AnalyticsEvent]
	completeCycleAnalytics runtime.TypedConsumedStream[*types.AnalyticsEvent]
	writeCycleAnalytics    runtime.TypedSinkStream[*types.AnalyticsEvent, error]
	continueCycleAnalytics runtime.TypedConsumedStream[*types.AnalyticsEvent]
}

type cycleAnalyticsPipelineHandlers struct {
	// data source handlers
}

type cycleAnalyticsPipelineDataConnectors struct {
	// data sources
	cycleAnalyticsInput runtime.Consumer[*types.AnalyticsEvent]
	// data sinks
	writeCycleAnalyticsCycleAnalyticsResult runtime.Consumer[*types.AnalyticsEvent]
}

func (s *Service) initCycleAnalyticsMakers() {
	if s.makers.cycleanalyticsAdvanceCycleAnalyticsMaker == nil {
		s.makers.cycleanalyticsAdvanceCycleAnalyticsMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*cycleanalytics.AdvanceCycleAnalytics, error) {
			return cycleanalytics.MakeAdvanceCycleAnalytics(ctx, env, cfg)
		}
	}
	if s.makers.cycleanalyticsCompleteCycleAnalyticsMaker == nil {
		s.makers.cycleanalyticsCompleteCycleAnalyticsMaker = func(ctx context.Context, cfg *runtimecfg.FilterStreamConfig, env environment.ServiceEnvironment) (*cycleanalytics.CompleteCycleAnalytics, error) {
			return cycleanalytics.MakeCompleteCycleAnalytics(ctx, env, cfg)
		}
	}
	if s.makers.cycleanalyticsContinueCycleAnalyticsMaker == nil {
		s.makers.cycleanalyticsContinueCycleAnalyticsMaker = func(ctx context.Context, cfg *runtimecfg.FilterStreamConfig, env environment.ServiceEnvironment) (*cycleanalytics.ContinueCycleAnalytics, error) {
			return cycleanalytics.MakeContinueCycleAnalytics(ctx, env, cfg)
		}
	}
	if s.makers.endpointCycleAnalyticsInputSourceMaker == nil {
		s.makers.endpointCycleAnalyticsInputSourceMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.CycleAnalyticsInputSource, error) {
			return endpoint.MakeCycleAnalyticsInputSource(ctx, env, cfg)
		}
	}
	if s.makers.endpointCycleAnalyticsResultSinkMaker == nil {
		s.makers.endpointCycleAnalyticsResultSinkMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.CycleAnalyticsResultSink, error) {
			return endpoint.MakeCycleAnalyticsResultSink(ctx, env, cfg)
		}
	}
}

// initCycleAnalyticsStreams constructs the streams owned by this
// pipeline. The service-level coordinator preserves the global construction,
// binding and post-initialization phases across all pipelines.
func (s *Service) initCycleAnalyticsStreams(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx
	_ = cfg
	_ = env
	if err = s.initCycleAnalyticsCycleAnalyticsLinkStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initCycleAnalyticsCycleAnalyticsInputStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initCycleAnalyticsMergeCycleAnalyticsStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initCycleAnalyticsAdvanceCycleAnalyticsStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initCycleAnalyticsSplitCycleAnalyticsStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initCycleAnalyticsCompleteCycleAnalyticsStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initCycleAnalyticsWriteCycleAnalyticsStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initCycleAnalyticsContinueCycleAnalyticsStream(ctx, cfg, env); err != nil {
		return err
	}
	return nil
}

func (s *Service) bindCycleAnalyticsStreams() error {
	return nil
}

func (s *Service) initCycleAnalyticsEndpoints() error {
	var err error
	if s.dataConnectors.cycleAnalyticsInput, err = endpoint.MakeEndpointConsumerCycleAnalyticsInputSource(s.streams.cycleAnalyticsInput, s.functions.endpointCycleAnalyticsInputSource); err != nil {
		return err
	}
	if s.dataConnectors.writeCycleAnalyticsCycleAnalyticsResult, err = endpoint.MakeEndpointConsumerCycleAnalyticsResultSink(s.streams.writeCycleAnalytics, s.functions.endpointCycleAnalyticsResultSink); err != nil {
		return err
	}
	_ = err
	return nil
}

func (s *Service) postInitCycleAnalyticsStreams() error {
	if err := s.postInitCycleAnalyticsCycleAnalyticsLinkStream(); err != nil {
		return err
	}
	return nil
}
func (s *Service) initCycleAnalyticsCycleAnalyticsLinkStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.cycleAnalyticsLink, err = transformation.Link[*types.AnalyticsEvent](&cfg.Streams.CycleAnalyticsLink, env); err != nil {
		return err
	}
	return nil
}
func (s *Service) postInitCycleAnalyticsCycleAnalyticsLinkStream() error {
	var err error

	if err = s.streams.cycleAnalyticsLink.SetSource(s.streams.continueCycleAnalytics); err != nil {
		return err
	}
	return err
}
func (s *Service) initCycleAnalyticsCycleAnalyticsInputStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.cycleAnalyticsInput, err = transformation.Input[*types.AnalyticsEvent, any, error](&cfg.Streams.CycleAnalyticsInput, env); err != nil {
		return err
	}
	return nil
}
func (s *Service) initCycleAnalyticsMergeCycleAnalyticsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.mergeCycleAnalytics, err = transformation.Merge[*types.AnalyticsEvent](&cfg.Streams.MergeCycleAnalytics, s.streams.cycleAnalyticsInput, s.streams.cycleAnalyticsLink); err != nil {
		return err
	}
	return nil
}
func (s *Service) initCycleAnalyticsAdvanceCycleAnalyticsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.advanceCycleAnalytics, err = transformation.Map[*types.AnalyticsEvent, *types.AnalyticsEvent](&cfg.Streams.AdvanceCycleAnalytics, s.streams.mergeCycleAnalytics, s.functions.cycleanalyticsAdvanceCycleAnalytics); err != nil {
		return err
	}
	return nil
}
func (s *Service) initCycleAnalyticsSplitCycleAnalyticsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.splitCycleAnalytics, err = transformation.Split[*types.AnalyticsEvent](&cfg.Streams.SplitCycleAnalytics, s.streams.advanceCycleAnalytics); err != nil {
		return err
	}
	return nil
}
func (s *Service) initCycleAnalyticsCompleteCycleAnalyticsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.completeCycleAnalytics, err = transformation.Filter[*types.AnalyticsEvent](&cfg.Streams.CompleteCycleAnalytics, s.streams.splitCycleAnalytics.AddStream(), s.functions.cycleanalyticsCompleteCycleAnalytics); err != nil {
		return err
	}
	return nil
}
func (s *Service) initCycleAnalyticsWriteCycleAnalyticsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.writeCycleAnalytics, err = transformation.Sink[*types.AnalyticsEvent, error](&cfg.Streams.WriteCycleAnalytics, s.streams.completeCycleAnalytics); err != nil {
		return err
	}
	return nil
}
func (s *Service) initCycleAnalyticsContinueCycleAnalyticsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.continueCycleAnalytics, err = transformation.Filter[*types.AnalyticsEvent](&cfg.Streams.ContinueCycleAnalytics, s.streams.splitCycleAnalytics.AddStream(), s.functions.cycleanalyticsContinueCycleAnalytics); err != nil {
		return err
	}
	return nil
}
func (s *Service) scheduleCycleAnalyticsFunctions(
	eg pipelineMakerTaskGroup,
	egCtx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) {
	if s.makers.cycleanalyticsAdvanceCycleAnalyticsMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.cycleanalyticsAdvanceCycleAnalytics, err = s.makers.cycleanalyticsAdvanceCycleAnalyticsMaker(egCtx, &cfg.Streams.AdvanceCycleAnalytics, env)
			return err
		})
	}
	if s.makers.cycleanalyticsCompleteCycleAnalyticsMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.cycleanalyticsCompleteCycleAnalytics, err = s.makers.cycleanalyticsCompleteCycleAnalyticsMaker(egCtx, &cfg.Streams.CompleteCycleAnalytics, env)
			return err
		})
	}
	if s.makers.cycleanalyticsContinueCycleAnalyticsMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.cycleanalyticsContinueCycleAnalytics, err = s.makers.cycleanalyticsContinueCycleAnalyticsMaker(egCtx, &cfg.Streams.ContinueCycleAnalytics, env)
			return err
		})
	}
	if s.makers.endpointCycleAnalyticsInputSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointCycleAnalyticsInputSource, err = s.makers.endpointCycleAnalyticsInputSourceMaker(egCtx, &cfg.Endpoints.CycleAnalyticsInput, env)
			return err
		})
	}
	if s.makers.endpointCycleAnalyticsResultSinkMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointCycleAnalyticsResultSink, err = s.makers.endpointCycleAnalyticsResultSinkMaker(egCtx, &cfg.Endpoints.CycleAnalyticsResult, env)
			return err
		})
	}
}
