// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"

	"github.com/gorundebug/analyticsservice/internal/config"
	"github.com/gorundebug/analyticsservice/internal/functions/endpoint"
	"github.com/gorundebug/analyticsservice/internal/functions/substreamanalytics"
	"github.com/gorundebug/analyticsservice/internal/types"
	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/environment"
	"github.com/gorundebug/servicelib/transformation"
)

type substreamAnalyticsPipelineMakers struct {
	// stream function makers
	substreamanalyticsBuildSubstreamAnalyticsResultMaker func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*substreamanalytics.BuildSubstreamAnalyticsResult, error)
	substreamanalyticsInvokeAnalyticsSubstreamMaker      func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*substreamanalytics.InvokeAnalyticsSubstream, error)
	// data source function makers
	endpointSubstreamAnalyticsInputSourceMaker func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.SubstreamAnalyticsInputSource, error)
	// data sink function makers
	endpointSubstreamAnalyticsResultSinkMaker func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.SubstreamAnalyticsResultSink, error)
}

type substreamAnalyticsPipelineFunctions struct {
	// stream functions
	substreamanalyticsBuildSubstreamAnalyticsResult *substreamanalytics.BuildSubstreamAnalyticsResult
	substreamanalyticsInvokeAnalyticsSubstream      *substreamanalytics.InvokeAnalyticsSubstream
	// data source functions
	endpointSubstreamAnalyticsInputSource *endpoint.SubstreamAnalyticsInputSource
	// data sink functions
	endpointSubstreamAnalyticsResultSink *endpoint.SubstreamAnalyticsResultSink
}

type substreamAnalyticsPipelineStreams struct {
	analyzeAnalyticsSubstream     runtime.TypedSubStream[*types.AnalyticsEvent, *types.AnalyticsResult]
	buildSubstreamAnalyticsResult runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, *types.AnalyticsResult]
	substreamAnalyticsInput       runtime.TypedInputStream[*types.AnalyticsEvent, any, error]
	invokeAnalyticsSubstream      runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, *types.AnalyticsResult]
	writeSubstreamAnalytics       runtime.TypedSinkStream[*types.AnalyticsResult, error]
}

type substreamAnalyticsPipelineHandlers struct {
	// data source handlers
}

type substreamAnalyticsPipelineDataConnectors struct {
	// data sources
	substreamAnalyticsInput runtime.Consumer[*types.AnalyticsEvent]
	// data sinks
	writeSubstreamAnalyticsSubstreamAnalyticsResult runtime.Consumer[*types.AnalyticsResult]
}

func (s *Service) initSubstreamAnalyticsMakers() {
	if s.makers.substreamanalyticsBuildSubstreamAnalyticsResultMaker == nil {
		s.makers.substreamanalyticsBuildSubstreamAnalyticsResultMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*substreamanalytics.BuildSubstreamAnalyticsResult, error) {
			return substreamanalytics.MakeBuildSubstreamAnalyticsResult(ctx, env, cfg)
		}
	}
	if s.makers.substreamanalyticsInvokeAnalyticsSubstreamMaker == nil {
		s.makers.substreamanalyticsInvokeAnalyticsSubstreamMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*substreamanalytics.InvokeAnalyticsSubstream, error) {
			return substreamanalytics.MakeInvokeAnalyticsSubstream(ctx, env, cfg)
		}
	}
	if s.makers.endpointSubstreamAnalyticsInputSourceMaker == nil {
		s.makers.endpointSubstreamAnalyticsInputSourceMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.SubstreamAnalyticsInputSource, error) {
			return endpoint.MakeSubstreamAnalyticsInputSource(ctx, env, cfg)
		}
	}
	if s.makers.endpointSubstreamAnalyticsResultSinkMaker == nil {
		s.makers.endpointSubstreamAnalyticsResultSinkMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.SubstreamAnalyticsResultSink, error) {
			return endpoint.MakeSubstreamAnalyticsResultSink(ctx, env, cfg)
		}
	}
}

// initSubstreamAnalyticsStreams constructs the streams owned by this
// pipeline. The service-level coordinator preserves the global construction,
// binding and post-initialization phases across all pipelines.
func (s *Service) initSubstreamAnalyticsStreams(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx
	_ = cfg
	_ = env
	if err = s.initSubstreamAnalyticsAnalyzeAnalyticsSubstreamStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initSubstreamAnalyticsBuildSubstreamAnalyticsResultStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initSubstreamAnalyticsSubstreamAnalyticsInputStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initSubstreamAnalyticsInvokeAnalyticsSubstreamStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initSubstreamAnalyticsWriteSubstreamAnalyticsStream(ctx, cfg, env); err != nil {
		return err
	}
	return nil
}

func (s *Service) bindSubstreamAnalyticsStreams() error {
	if err := s.bindSubstreamAnalyticsAnalyzeAnalyticsSubstreamStream(); err != nil {
		return err
	}
	return nil
}

func (s *Service) initSubstreamAnalyticsEndpoints() error {
	var err error
	if s.dataConnectors.substreamAnalyticsInput, err = endpoint.MakeEndpointConsumerSubstreamAnalyticsInputSource(s.streams.substreamAnalyticsInput, s.functions.endpointSubstreamAnalyticsInputSource); err != nil {
		return err
	}
	if s.dataConnectors.writeSubstreamAnalyticsSubstreamAnalyticsResult, err = endpoint.MakeEndpointConsumerSubstreamAnalyticsResultSink(s.streams.writeSubstreamAnalytics, s.functions.endpointSubstreamAnalyticsResultSink); err != nil {
		return err
	}
	_ = err
	return nil
}

func (s *Service) postInitSubstreamAnalyticsStreams() error {
	return nil
}
func (s *Service) initSubstreamAnalyticsAnalyzeAnalyticsSubstreamStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.analyzeAnalyticsSubstream, err = transformation.SubStream[*types.AnalyticsEvent, *types.AnalyticsResult](&cfg.Streams.AnalyzeAnalyticsSubstream, env); err != nil {
		return err
	}
	return nil
}
func (s *Service) bindSubstreamAnalyticsAnalyzeAnalyticsSubstreamStream() error {
	return s.streams.analyzeAnalyticsSubstream.SetSource(s.streams.buildSubstreamAnalyticsResult)
}
func (s *Service) initSubstreamAnalyticsBuildSubstreamAnalyticsResultStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.buildSubstreamAnalyticsResult, err = transformation.Map[*types.AnalyticsEvent, *types.AnalyticsResult](&cfg.Streams.BuildSubstreamAnalyticsResult, s.streams.analyzeAnalyticsSubstream, s.functions.substreamanalyticsBuildSubstreamAnalyticsResult); err != nil {
		return err
	}
	return nil
}
func (s *Service) initSubstreamAnalyticsSubstreamAnalyticsInputStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.substreamAnalyticsInput, err = transformation.Input[*types.AnalyticsEvent, any, error](&cfg.Streams.SubstreamAnalyticsInput, env); err != nil {
		return err
	}
	return nil
}
func (s *Service) initSubstreamAnalyticsInvokeAnalyticsSubstreamStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.invokeAnalyticsSubstream, err = transformation.Map[*types.AnalyticsEvent, *types.AnalyticsResult](&cfg.Streams.InvokeAnalyticsSubstream, s.streams.substreamAnalyticsInput, s.functions.substreamanalyticsInvokeAnalyticsSubstream); err != nil {
		return err
	}
	return nil
}
func (s *Service) initSubstreamAnalyticsWriteSubstreamAnalyticsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.writeSubstreamAnalytics, err = transformation.Sink[*types.AnalyticsResult, error](&cfg.Streams.WriteSubstreamAnalytics, s.streams.invokeAnalyticsSubstream); err != nil {
		return err
	}
	return nil
}
func (s *Service) scheduleSubstreamAnalyticsFunctions(
	eg pipelineMakerTaskGroup,
	egCtx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) {
	if s.makers.substreamanalyticsBuildSubstreamAnalyticsResultMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.substreamanalyticsBuildSubstreamAnalyticsResult, err = s.makers.substreamanalyticsBuildSubstreamAnalyticsResultMaker(egCtx, &cfg.Streams.BuildSubstreamAnalyticsResult, env)
			return err
		})
	}
	if s.makers.substreamanalyticsInvokeAnalyticsSubstreamMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.substreamanalyticsInvokeAnalyticsSubstream, err = s.makers.substreamanalyticsInvokeAnalyticsSubstreamMaker(egCtx, &cfg.Streams.InvokeAnalyticsSubstream, env)
			return err
		})
	}
	if s.makers.endpointSubstreamAnalyticsInputSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointSubstreamAnalyticsInputSource, err = s.makers.endpointSubstreamAnalyticsInputSourceMaker(egCtx, &cfg.Endpoints.SubstreamAnalyticsInput, env)
			return err
		})
	}
	if s.makers.endpointSubstreamAnalyticsResultSinkMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointSubstreamAnalyticsResultSink, err = s.makers.endpointSubstreamAnalyticsResultSinkMaker(egCtx, &cfg.Endpoints.SubstreamAnalyticsResult, env)
			return err
		})
	}
}
