// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"

	"github.com/gorundebug/analyticsservice/internal/config"
	"github.com/gorundebug/analyticsservice/internal/functions/analytics"
	"github.com/gorundebug/analyticsservice/internal/functions/cron"
	"github.com/gorundebug/analyticsservice/internal/functions/endpoint"
	"github.com/gorundebug/model_go/pkg/types"
	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/environment"
	"github.com/gorundebug/servicelib/transformation"
)

type analyticsPipelineMakers struct {
	// stream function makers
	analyticsCountOrderProcessedMaker func(ctx context.Context, cfg *runtimecfg.ProcessStreamConfig, env environment.ServiceEnvironment) (*analytics.CountOrderProcessed, error)
	// data source function makers
	cronAnalyticsScheduleSourceMaker          func(ctx context.Context, cfg *runtimecfg.CronEndpointConfig, env environment.ServiceEnvironment) (*cron.AnalyticsScheduleSource, error)
	endpointOrderProcessedEndpointSourceMaker func(ctx context.Context, cfg *runtimecfg.KafkaEndpointConfig, env environment.ServiceEnvironment) (*endpoint.OrderProcessedEndpointSource, error)
	// data sink function makers
}

type analyticsPipelineFunctions struct {
	// stream functions
	analyticsCountOrderProcessed *analytics.CountOrderProcessed
	// data source functions
	cronAnalyticsScheduleSource          *cron.AnalyticsScheduleSource
	endpointOrderProcessedEndpointSource *endpoint.OrderProcessedEndpointSource
	// data sink functions
}

type analyticsPipelineStreams struct {
	analyticsSchedule     runtime.TypedInputStream[string, any, error]
	consumeOrderProcessed runtime.TypedInputStream[*types.OrderProcessed, *types.OrderProcessed, error]
	countOrderProcessed   runtime.TypedProcessConsumedStream[*types.OrderProcessed, *types.OrderProcessed, error]
}

type analyticsPipelineHandlers struct {
	// data source handlers
}

type analyticsPipelineDataConnectors struct {
	// data sources
	analyticsSchedule runtime.Consumer[string]
	orderProcessed    runtime.Consumer[*types.OrderProcessed]
	// data sinks
}

func (s *Service) initAnalyticsMakers() {
	if s.makers.analyticsCountOrderProcessedMaker == nil {
		s.makers.analyticsCountOrderProcessedMaker = func(ctx context.Context, cfg *runtimecfg.ProcessStreamConfig, env environment.ServiceEnvironment) (*analytics.CountOrderProcessed, error) {
			return analytics.MakeCountOrderProcessed(ctx, env, cfg)
		}
	}
	if s.makers.cronAnalyticsScheduleSourceMaker == nil {
		s.makers.cronAnalyticsScheduleSourceMaker = func(ctx context.Context, cfg *runtimecfg.CronEndpointConfig, env environment.ServiceEnvironment) (*cron.AnalyticsScheduleSource, error) {
			return cron.MakeAnalyticsScheduleSource(ctx, env, cfg)
		}
	}
	if s.makers.endpointOrderProcessedEndpointSourceMaker == nil {
		s.makers.endpointOrderProcessedEndpointSourceMaker = func(ctx context.Context, cfg *runtimecfg.KafkaEndpointConfig, env environment.ServiceEnvironment) (*endpoint.OrderProcessedEndpointSource, error) {
			return endpoint.MakeOrderProcessedEndpointSource(ctx, env, cfg)
		}
	}
}

// initAnalyticsStreams constructs the streams owned by this
// pipeline. The service-level coordinator preserves the global construction,
// binding and post-initialization phases across all pipelines.
func (s *Service) initAnalyticsStreams(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx
	_ = cfg
	_ = env
	if err = s.initAnalyticsAnalyticsScheduleStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initAnalyticsConsumeOrderProcessedStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initAnalyticsCountOrderProcessedStream(ctx, cfg, env); err != nil {
		return err
	}
	return nil
}

func (s *Service) bindAnalyticsStreams() error {
	if err := s.bindAnalyticsConsumeOrderProcessedStream(); err != nil {
		return err
	}
	return nil
}

func (s *Service) initAnalyticsEndpoints() error {
	var err error
	if s.dataConnectors.analyticsSchedule, err = cron.MakeEndpointConsumerAnalyticsScheduleSource(s.streams.analyticsSchedule, s.functions.cronAnalyticsScheduleSource); err != nil {
		return err
	}
	if s.dataConnectors.orderProcessed, err = endpoint.MakeEndpointConsumerOrderProcessedEndpointSource(s.streams.consumeOrderProcessed, s.functions.endpointOrderProcessedEndpointSource); err != nil {
		return err
	}
	_ = err
	return nil
}

func (s *Service) postInitAnalyticsStreams() error {
	return nil
}
func (s *Service) initAnalyticsAnalyticsScheduleStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.analyticsSchedule, err = transformation.Input[string, any, error](&cfg.Streams.AnalyticsSchedule, env); err != nil {
		return err
	}
	return nil
}
func (s *Service) initAnalyticsConsumeOrderProcessedStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.consumeOrderProcessed, err = transformation.Input[*types.OrderProcessed, *types.OrderProcessed, error](&cfg.Streams.ConsumeOrderProcessed, env); err != nil {
		return err
	}
	return nil
}
func (s *Service) bindAnalyticsConsumeOrderProcessedStream() error {
	return s.streams.consumeOrderProcessed.SetSource(s.streams.countOrderProcessed)
}
func (s *Service) initAnalyticsCountOrderProcessedStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.countOrderProcessed, err = transformation.Process[*types.OrderProcessed, *types.OrderProcessed, error](&cfg.Streams.CountOrderProcessed, s.streams.consumeOrderProcessed, s.functions.analyticsCountOrderProcessed); err != nil {
		return err
	}
	return nil
}
func (s *Service) scheduleAnalyticsFunctions(
	eg pipelineMakerTaskGroup,
	egCtx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) {
	if s.makers.analyticsCountOrderProcessedMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.analyticsCountOrderProcessed, err = s.makers.analyticsCountOrderProcessedMaker(egCtx, &cfg.Streams.CountOrderProcessed, env)
			return err
		})
	}
	if s.makers.cronAnalyticsScheduleSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.cronAnalyticsScheduleSource, err = s.makers.cronAnalyticsScheduleSourceMaker(egCtx, &cfg.Endpoints.AnalyticsSchedule, env)
			return err
		})
	}
	if s.makers.endpointOrderProcessedEndpointSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointOrderProcessedEndpointSource, err = s.makers.endpointOrderProcessedEndpointSourceMaker(egCtx, &cfg.Endpoints.OrderProcessed, env)
			return err
		})
	}
}
