// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"

	"github.com/gorundebug/analyticsservice/internal/config"
	"github.com/gorundebug/analyticsservice/internal/functions/endpoint"
	"github.com/gorundebug/analyticsservice/internal/functions/multijoinanalytics"
	"github.com/gorundebug/analyticsservice/internal/types"
	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/datastruct"
	"github.com/gorundebug/servicelib/runtime/environment"
	"github.com/gorundebug/servicelib/transformation"
)

type multiJoinAnalyticsPipelineMakers struct {
	// stream function makers
	multijoinanalyticsKeyOrdersForMultiJoinMaker    func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.KeyOrdersForMultiJoin, error)
	multijoinanalyticsKeyPaymentsForMultiJoinMaker  func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.KeyPaymentsForMultiJoin, error)
	multijoinanalyticsKeyShipmentsForMultiJoinMaker func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.KeyShipmentsForMultiJoin, error)
	multijoinanalyticsMultiJoinAnalyticsEventsMaker func(ctx context.Context, cfg *runtimecfg.MultiJoinStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.MultiJoinAnalyticsEvents, error)
	multijoinanalyticsRouteAnalyticsResultMaker     func(ctx context.Context, cfg *runtimecfg.CaseStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.RouteAnalyticsResult, error)
	// data source function makers
	// data sink function makers
	endpointHighValueAnalyticsSinkMaker func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.HighValueAnalyticsSink, error)
	endpointStandardAnalyticsSinkMaker  func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.StandardAnalyticsSink, error)
}

type multiJoinAnalyticsPipelineFunctions struct {
	// stream functions
	multijoinanalyticsKeyOrdersForMultiJoin    *multijoinanalytics.KeyOrdersForMultiJoin
	multijoinanalyticsKeyPaymentsForMultiJoin  *multijoinanalytics.KeyPaymentsForMultiJoin
	multijoinanalyticsKeyShipmentsForMultiJoin *multijoinanalytics.KeyShipmentsForMultiJoin
	multijoinanalyticsMultiJoinAnalyticsEvents *multijoinanalytics.MultiJoinAnalyticsEvents
	multijoinanalyticsRouteAnalyticsResult     *multijoinanalytics.RouteAnalyticsResult
	// data source functions
	// data sink functions
	endpointHighValueAnalyticsSink *endpoint.HighValueAnalyticsSink
	endpointStandardAnalyticsSink  *endpoint.StandardAnalyticsSink
}

type multiJoinAnalyticsPipelineStreams struct {
	keyOrdersForMultiJoin    runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, datastruct.KeyValue[string, *types.AnalyticsEvent]]
	keyPaymentsForMultiJoin  runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, datastruct.KeyValue[string, *types.AnalyticsEvent]]
	keyShipmentsForMultiJoin runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, datastruct.KeyValue[string, *types.AnalyticsEvent]]
	multiJoinAnalyticsEvents runtime.TypedMultiJoinConsumedStream[string, *types.AnalyticsEvent, *types.AnalyticsResult]
	routeAnalyticsResult     runtime.TypedCaseStream[*types.AnalyticsResult]
	highValueAnalytics       runtime.TypedConsumedStream[*types.AnalyticsResult]
	writeHighValueAnalytics  runtime.TypedSinkStream[*types.AnalyticsResult, error]
	standardAnalytics        runtime.TypedConsumedStream[*types.AnalyticsResult]
	writeStandardAnalytics   runtime.TypedSinkStream[*types.AnalyticsResult, error]
}

type multiJoinAnalyticsPipelineHandlers struct {
	// data source handlers
}

type multiJoinAnalyticsPipelineDataConnectors struct {
	// data sources
	// data sinks
	writeHighValueAnalyticsHighValueAnalytics runtime.Consumer[*types.AnalyticsResult]
	writeStandardAnalyticsStandardAnalytics   runtime.Consumer[*types.AnalyticsResult]
}

func (s *Service) initMultiJoinAnalyticsMakers() {
	if s.makers.multijoinanalyticsKeyOrdersForMultiJoinMaker == nil {
		s.makers.multijoinanalyticsKeyOrdersForMultiJoinMaker = func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.KeyOrdersForMultiJoin, error) {
			return multijoinanalytics.MakeKeyOrdersForMultiJoin(ctx, env, cfg)
		}
	}
	if s.makers.multijoinanalyticsKeyPaymentsForMultiJoinMaker == nil {
		s.makers.multijoinanalyticsKeyPaymentsForMultiJoinMaker = func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.KeyPaymentsForMultiJoin, error) {
			return multijoinanalytics.MakeKeyPaymentsForMultiJoin(ctx, env, cfg)
		}
	}
	if s.makers.multijoinanalyticsKeyShipmentsForMultiJoinMaker == nil {
		s.makers.multijoinanalyticsKeyShipmentsForMultiJoinMaker = func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.KeyShipmentsForMultiJoin, error) {
			return multijoinanalytics.MakeKeyShipmentsForMultiJoin(ctx, env, cfg)
		}
	}
	if s.makers.multijoinanalyticsMultiJoinAnalyticsEventsMaker == nil {
		s.makers.multijoinanalyticsMultiJoinAnalyticsEventsMaker = func(ctx context.Context, cfg *runtimecfg.MultiJoinStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.MultiJoinAnalyticsEvents, error) {
			return multijoinanalytics.MakeMultiJoinAnalyticsEvents(ctx, env, cfg)
		}
	}
	if s.makers.multijoinanalyticsRouteAnalyticsResultMaker == nil {
		s.makers.multijoinanalyticsRouteAnalyticsResultMaker = func(ctx context.Context, cfg *runtimecfg.CaseStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.RouteAnalyticsResult, error) {
			return multijoinanalytics.MakeRouteAnalyticsResult(ctx, env, cfg)
		}
	}
	if s.makers.endpointHighValueAnalyticsSinkMaker == nil {
		s.makers.endpointHighValueAnalyticsSinkMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.HighValueAnalyticsSink, error) {
			return endpoint.MakeHighValueAnalyticsSink(ctx, env, cfg)
		}
	}
	if s.makers.endpointStandardAnalyticsSinkMaker == nil {
		s.makers.endpointStandardAnalyticsSinkMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.StandardAnalyticsSink, error) {
			return endpoint.MakeStandardAnalyticsSink(ctx, env, cfg)
		}
	}
}

// initMultiJoinAnalyticsStreams constructs the streams owned by this
// pipeline. The service-level coordinator preserves the global construction,
// binding and post-initialization phases across all pipelines.
func (s *Service) initMultiJoinAnalyticsStreams(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx
	_ = cfg
	_ = env
	if err = s.initMultiJoinAnalyticsKeyOrdersForMultiJoinStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initMultiJoinAnalyticsKeyPaymentsForMultiJoinStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initMultiJoinAnalyticsKeyShipmentsForMultiJoinStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initMultiJoinAnalyticsMultiJoinAnalyticsEventsStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initMultiJoinAnalyticsRouteAnalyticsResultStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initMultiJoinAnalyticsHighValueAnalyticsStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initMultiJoinAnalyticsWriteHighValueAnalyticsStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initMultiJoinAnalyticsStandardAnalyticsStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initMultiJoinAnalyticsWriteStandardAnalyticsStream(ctx, cfg, env); err != nil {
		return err
	}
	return nil
}

func (s *Service) bindMultiJoinAnalyticsStreams() error {
	return nil
}

func (s *Service) initMultiJoinAnalyticsEndpoints() error {
	var err error
	if s.dataConnectors.writeHighValueAnalyticsHighValueAnalytics, err = endpoint.MakeEndpointConsumerHighValueAnalyticsSink(s.streams.writeHighValueAnalytics, s.functions.endpointHighValueAnalyticsSink); err != nil {
		return err
	}
	if s.dataConnectors.writeStandardAnalyticsStandardAnalytics, err = endpoint.MakeEndpointConsumerStandardAnalyticsSink(s.streams.writeStandardAnalytics, s.functions.endpointStandardAnalyticsSink); err != nil {
		return err
	}
	_ = err
	return nil
}

func (s *Service) postInitMultiJoinAnalyticsStreams() error {
	return nil
}
func (s *Service) initMultiJoinAnalyticsKeyOrdersForMultiJoinStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.keyOrdersForMultiJoin, err = transformation.KeyBy[*types.AnalyticsEvent, string, *types.AnalyticsEvent](&cfg.Streams.KeyOrdersForMultiJoin, s.streams.splitAnalyticsOrders.AddStream(), s.functions.multijoinanalyticsKeyOrdersForMultiJoin); err != nil {
		return err
	}
	return nil
}
func (s *Service) initMultiJoinAnalyticsKeyPaymentsForMultiJoinStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.keyPaymentsForMultiJoin, err = transformation.KeyBy[*types.AnalyticsEvent, string, *types.AnalyticsEvent](&cfg.Streams.KeyPaymentsForMultiJoin, s.streams.splitAnalyticsPayments.AddStream(), s.functions.multijoinanalyticsKeyPaymentsForMultiJoin); err != nil {
		return err
	}
	return nil
}
func (s *Service) initMultiJoinAnalyticsKeyShipmentsForMultiJoinStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.keyShipmentsForMultiJoin, err = transformation.KeyBy[*types.AnalyticsEvent, string, *types.AnalyticsEvent](&cfg.Streams.KeyShipmentsForMultiJoin, s.streams.analyticsShipments, s.functions.multijoinanalyticsKeyShipmentsForMultiJoin); err != nil {
		return err
	}
	return nil
}
func (s *Service) initMultiJoinAnalyticsMultiJoinAnalyticsEventsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.multiJoinAnalyticsEvents, err = transformation.MultiJoin[string, *types.AnalyticsEvent, *types.AnalyticsResult](&cfg.Streams.MultiJoinAnalyticsEvents, s.streams.keyOrdersForMultiJoin, s.functions.multijoinanalyticsMultiJoinAnalyticsEvents); err != nil {
		return err
	}
	if err = transformation.MultiJoinLink[string, *types.AnalyticsEvent, *types.AnalyticsEvent, *types.AnalyticsResult](s.streams.multiJoinAnalyticsEvents, s.streams.keyPaymentsForMultiJoin); err != nil {
		return err
	}
	if err = transformation.MultiJoinLink[string, *types.AnalyticsEvent, *types.AnalyticsEvent, *types.AnalyticsResult](s.streams.multiJoinAnalyticsEvents, s.streams.keyShipmentsForMultiJoin); err != nil {
		return err
	}
	return nil
}
func (s *Service) initMultiJoinAnalyticsRouteAnalyticsResultStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.routeAnalyticsResult, err = transformation.CaseStream[*types.AnalyticsResult](&cfg.Streams.RouteAnalyticsResult, s.streams.multiJoinAnalyticsEvents, s.functions.multijoinanalyticsRouteAnalyticsResult); err != nil {
		return err
	}
	return nil
}
func (s *Service) initMultiJoinAnalyticsHighValueAnalyticsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.highValueAnalytics, err = transformation.WhenStream[*types.AnalyticsResult, *types.AnalyticsResult](&cfg.Streams.HighValueAnalytics, s.streams.routeAnalyticsResult); err != nil {
		return err
	}
	return nil
}
func (s *Service) initMultiJoinAnalyticsWriteHighValueAnalyticsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.writeHighValueAnalytics, err = transformation.Sink[*types.AnalyticsResult, error](&cfg.Streams.WriteHighValueAnalytics, s.streams.highValueAnalytics); err != nil {
		return err
	}
	return nil
}
func (s *Service) initMultiJoinAnalyticsStandardAnalyticsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.standardAnalytics, err = transformation.WhenStream[*types.AnalyticsResult, *types.AnalyticsResult](&cfg.Streams.StandardAnalytics, s.streams.routeAnalyticsResult); err != nil {
		return err
	}
	return nil
}
func (s *Service) initMultiJoinAnalyticsWriteStandardAnalyticsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.writeStandardAnalytics, err = transformation.Sink[*types.AnalyticsResult, error](&cfg.Streams.WriteStandardAnalytics, s.streams.standardAnalytics); err != nil {
		return err
	}
	return nil
}
func (s *Service) scheduleMultiJoinAnalyticsFunctions(
	eg pipelineMakerTaskGroup,
	egCtx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) {
	if s.makers.multijoinanalyticsKeyOrdersForMultiJoinMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.multijoinanalyticsKeyOrdersForMultiJoin, err = s.makers.multijoinanalyticsKeyOrdersForMultiJoinMaker(egCtx, &cfg.Streams.KeyOrdersForMultiJoin, env)
			return err
		})
	}
	if s.makers.multijoinanalyticsKeyPaymentsForMultiJoinMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.multijoinanalyticsKeyPaymentsForMultiJoin, err = s.makers.multijoinanalyticsKeyPaymentsForMultiJoinMaker(egCtx, &cfg.Streams.KeyPaymentsForMultiJoin, env)
			return err
		})
	}
	if s.makers.multijoinanalyticsKeyShipmentsForMultiJoinMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.multijoinanalyticsKeyShipmentsForMultiJoin, err = s.makers.multijoinanalyticsKeyShipmentsForMultiJoinMaker(egCtx, &cfg.Streams.KeyShipmentsForMultiJoin, env)
			return err
		})
	}
	if s.makers.multijoinanalyticsMultiJoinAnalyticsEventsMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.multijoinanalyticsMultiJoinAnalyticsEvents, err = s.makers.multijoinanalyticsMultiJoinAnalyticsEventsMaker(egCtx, &cfg.Streams.MultiJoinAnalyticsEvents, env)
			return err
		})
	}
	if s.makers.multijoinanalyticsRouteAnalyticsResultMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.multijoinanalyticsRouteAnalyticsResult, err = s.makers.multijoinanalyticsRouteAnalyticsResultMaker(egCtx, &cfg.Streams.RouteAnalyticsResult, env)
			return err
		})
	}
	if s.makers.endpointHighValueAnalyticsSinkMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointHighValueAnalyticsSink, err = s.makers.endpointHighValueAnalyticsSinkMaker(egCtx, &cfg.Endpoints.HighValueAnalytics, env)
			return err
		})
	}
	if s.makers.endpointStandardAnalyticsSinkMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointStandardAnalyticsSink, err = s.makers.endpointStandardAnalyticsSinkMaker(egCtx, &cfg.Endpoints.StandardAnalytics, env)
			return err
		})
	}
}
