// Code generated by servicegen. DO NOT EDIT.
package app

import (
	serdes "github.com/gorundebug/analyticsservice/internal/serdes"
	types "github.com/gorundebug/analyticsservice/internal/types"
	serdes2 "github.com/gorundebug/model_go/pkg/serdes"
	types2 "github.com/gorundebug/model_go/pkg/types"
	runtimeserde "github.com/gorundebug/servicelib/runtime/serde"
	"reflect"
)

func (s *Service) GetSerde(valueType reflect.Type) (runtimeserde.Serializer, error) {
	if serde, err := s.getCustomSerde(valueType); err != nil {
		return nil, err
	} else if serde != nil {
		return serde, nil
	}
	switch valueType {
	case runtimeserde.GetSerdeType[types.AnalyticsEvent](), runtimeserde.GetSerdeType[*types.AnalyticsEvent]():
		{
			var serde runtimeserde.Serde[*types.AnalyticsEvent] = &serdes.AnalyticsEventSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types.AnalyticsResult](), runtimeserde.GetSerdeType[*types.AnalyticsResult]():
		{
			var serde runtimeserde.Serde[*types.AnalyticsResult] = &serdes.AnalyticsResultSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types2.OrderProcessed](), runtimeserde.GetSerdeType[*types2.OrderProcessed]():
		{
			var serde runtimeserde.Serde[*types2.OrderProcessed] = &serdes2.OrderProcessedSerde{}
			return serde, nil
		}

	}
	return nil, nil
}
