// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/signal"
	"reflect"
	"sync"
	"syscall"
	"time"

	"github.com/gorundebug/servicelib/runtime"
	"github.com/gorundebug/servicelib/runtime/datastruct"
	"github.com/gorundebug/servicelib/runtime/environment"
	log "github.com/gorundebug/servicelib/runtime/environment/log"
	runtimeserde "github.com/gorundebug/servicelib/runtime/serde"

	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/transformation"
	"golang.org/x/sync/errgroup"

	"github.com/gorundebug/analyticsservice/internal/config"
	"github.com/gorundebug/analyticsservice/internal/functions/analytics"
	"github.com/gorundebug/analyticsservice/internal/functions/cron"
	"github.com/gorundebug/analyticsservice/internal/functions/endpoint"
	"github.com/gorundebug/analyticsservice/internal/functions/joinanalytics"
	"github.com/gorundebug/analyticsservice/internal/functions/multijoinanalytics"
	"github.com/gorundebug/analyticsservice/internal/serdes"
	types2 "github.com/gorundebug/analyticsservice/internal/types"
	serdes2 "github.com/gorundebug/model_go/pkg/serdes"
	"github.com/gorundebug/model_go/pkg/types"
)

type serviceMakers struct {
	//stream function makers
	analyticsCountOrderProcessedMaker               func(ctx context.Context, cfg *runtimecfg.ProcessStreamConfig, env environment.ServiceEnvironment) (*analytics.CountOrderProcessed, error)
	joinanalyticsKeyOrdersForJoinMaker              func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*joinanalytics.KeyOrdersForJoin, error)
	multijoinanalyticsKeyOrdersForMultiJoinMaker    func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.KeyOrdersForMultiJoin, error)
	joinanalyticsKeyPaymentsForJoinMaker            func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*joinanalytics.KeyPaymentsForJoin, error)
	joinanalyticsJoinOrderPaymentAnalyticsMaker     func(ctx context.Context, cfg *runtimecfg.JoinStreamConfig, env environment.ServiceEnvironment) (*joinanalytics.JoinOrderPaymentAnalytics, error)
	multijoinanalyticsKeyPaymentsForMultiJoinMaker  func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.KeyPaymentsForMultiJoin, error)
	multijoinanalyticsKeyShipmentsForMultiJoinMaker func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.KeyShipmentsForMultiJoin, error)
	multijoinanalyticsMultiJoinAnalyticsEventsMaker func(ctx context.Context, cfg *runtimecfg.MultiJoinStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.MultiJoinAnalyticsEvents, error)
	multijoinanalyticsRouteAnalyticsResultMaker     func(ctx context.Context, cfg *runtimecfg.CaseStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.RouteAnalyticsResult, error)
	//data source function makers
	cronAnalyticsScheduleSourceMaker          func(ctx context.Context, cfg *runtimecfg.CronEndpointConfig, env environment.ServiceEnvironment) (*cron.AnalyticsScheduleSource, error)
	endpointOrderProcessedEndpointSourceMaker func(ctx context.Context, cfg *runtimecfg.KafkaEndpointConfig, env environment.ServiceEnvironment) (*endpoint.OrderProcessedEndpointSource, error)
	endpointAnalyticsOrdersSourceMaker        func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.AnalyticsOrdersSource, error)
	endpointAnalyticsPaymentsSourceMaker      func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.AnalyticsPaymentsSource, error)
	endpointAnalyticsShipmentsSourceMaker     func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.AnalyticsShipmentsSource, error)
	//data sink function makers
	endpointJoinedAnalyticsSinkMaker    func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.JoinedAnalyticsSink, error)
	endpointHighValueAnalyticsSinkMaker func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.HighValueAnalyticsSink, error)
	endpointStandardAnalyticsSinkMaker  func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.StandardAnalyticsSink, error)
}

type serviceFunctions struct {
	//stream functions
	analyticsCountOrderProcessed               *analytics.CountOrderProcessed
	joinanalyticsKeyOrdersForJoin              *joinanalytics.KeyOrdersForJoin
	multijoinanalyticsKeyOrdersForMultiJoin    *multijoinanalytics.KeyOrdersForMultiJoin
	joinanalyticsKeyPaymentsForJoin            *joinanalytics.KeyPaymentsForJoin
	joinanalyticsJoinOrderPaymentAnalytics     *joinanalytics.JoinOrderPaymentAnalytics
	multijoinanalyticsKeyPaymentsForMultiJoin  *multijoinanalytics.KeyPaymentsForMultiJoin
	multijoinanalyticsKeyShipmentsForMultiJoin *multijoinanalytics.KeyShipmentsForMultiJoin
	multijoinanalyticsMultiJoinAnalyticsEvents *multijoinanalytics.MultiJoinAnalyticsEvents
	multijoinanalyticsRouteAnalyticsResult     *multijoinanalytics.RouteAnalyticsResult
	//data source functions
	cronAnalyticsScheduleSource          *cron.AnalyticsScheduleSource
	endpointOrderProcessedEndpointSource *endpoint.OrderProcessedEndpointSource
	endpointAnalyticsOrdersSource        *endpoint.AnalyticsOrdersSource
	endpointAnalyticsPaymentsSource      *endpoint.AnalyticsPaymentsSource
	endpointAnalyticsShipmentsSource     *endpoint.AnalyticsShipmentsSource
	//data sink functions
	endpointJoinedAnalyticsSink    *endpoint.JoinedAnalyticsSink
	endpointHighValueAnalyticsSink *endpoint.HighValueAnalyticsSink
	endpointStandardAnalyticsSink  *endpoint.StandardAnalyticsSink
}

type serviceStreams struct {
	//streams
	analyticsSchedule         runtime.TypedInputStream[string, any, error]
	consumeOrderProcessed     runtime.TypedInputStream[*types.OrderProcessed, *types.OrderProcessed, error]
	countOrderProcessed       runtime.TypedProcessConsumedStream[*types.OrderProcessed, *types.OrderProcessed, error]
	analyticsOrders           runtime.TypedInputStream[*types2.AnalyticsEvent, any, error]
	splitAnalyticsOrders      runtime.TypedSplitStream[*types2.AnalyticsEvent]
	keyOrdersForJoin          runtime.TypedTransformConsumedStream[*types2.AnalyticsEvent, datastruct.KeyValue[string, *types2.AnalyticsEvent]]
	keyOrdersForMultiJoin     runtime.TypedTransformConsumedStream[*types2.AnalyticsEvent, datastruct.KeyValue[string, *types2.AnalyticsEvent]]
	analyticsPayments         runtime.TypedInputStream[*types2.AnalyticsEvent, any, error]
	splitAnalyticsPayments    runtime.TypedSplitStream[*types2.AnalyticsEvent]
	keyPaymentsForJoin        runtime.TypedTransformConsumedStream[*types2.AnalyticsEvent, datastruct.KeyValue[string, *types2.AnalyticsEvent]]
	joinOrderPaymentAnalytics runtime.TypedJoinConsumedStream[string, *types2.AnalyticsEvent, *types2.AnalyticsEvent, *types2.AnalyticsResult]
	writeJoinedAnalytics      runtime.TypedSinkStream[*types2.AnalyticsResult, error]
	keyPaymentsForMultiJoin   runtime.TypedTransformConsumedStream[*types2.AnalyticsEvent, datastruct.KeyValue[string, *types2.AnalyticsEvent]]
	analyticsShipments        runtime.TypedInputStream[*types2.AnalyticsEvent, any, error]
	keyShipmentsForMultiJoin  runtime.TypedTransformConsumedStream[*types2.AnalyticsEvent, datastruct.KeyValue[string, *types2.AnalyticsEvent]]
	multiJoinAnalyticsEvents  runtime.TypedMultiJoinConsumedStream[string, *types2.AnalyticsEvent, *types2.AnalyticsResult]
	routeAnalyticsResult      runtime.TypedCaseStream[*types2.AnalyticsResult]
	highValueAnalytics        runtime.TypedConsumedStream[*types2.AnalyticsResult]
	writeHighValueAnalytics   runtime.TypedSinkStream[*types2.AnalyticsResult, error]
	standardAnalytics         runtime.TypedConsumedStream[*types2.AnalyticsResult]
	writeStandardAnalytics    runtime.TypedSinkStream[*types2.AnalyticsResult, error]
}

type serviceHandlers struct {
	//data source handlers
}

type serviceDataConnectors struct {
	//data sources
	analyticsSchedule  runtime.Consumer[string]
	orderProcessed     runtime.Consumer[*types.OrderProcessed]
	analyticsOrders    runtime.Consumer[*types2.AnalyticsEvent]
	analyticsPayments  runtime.Consumer[*types2.AnalyticsEvent]
	analyticsShipments runtime.Consumer[*types2.AnalyticsEvent]
	//data sinks
	writeJoinedAnalyticsJoinedAnalytics       runtime.Consumer[*types2.AnalyticsResult]
	writeHighValueAnalyticsHighValueAnalytics runtime.Consumer[*types2.AnalyticsResult]
	writeStandardAnalyticsStandardAnalytics   runtime.Consumer[*types2.AnalyticsResult]
}

type Service struct {
	runtime.ServiceApp
	makers          serviceMakers
	functions       serviceFunctions
	streams         serviceStreams
	handlers        serviceHandlers
	dataConnectors  serviceDataConnectors
	httpServer      *http.Server
	httpServerMaker func(context.Context, runtime.RuntimeEnvironment) (*http.Server, error)
	httpMux         *http.ServeMux
	httpMuxMaker    func(context.Context, runtime.RuntimeEnvironment) (*http.ServeMux, error)
	httpServerDone  chan struct{}
}

func (s *Service) GetSerde(valueType reflect.Type) (runtimeserde.Serializer, error) {
	if serde, err := s.getCustomSerde(valueType); err != nil {
		return nil, err
	} else if serde != nil {
		return serde, nil
	}
	switch valueType {
	case runtimeserde.GetSerdeType[types2.AnalyticsEvent](), runtimeserde.GetSerdeType[*types2.AnalyticsEvent]():
		{
			var serde runtimeserde.Serde[*types2.AnalyticsEvent] = &serdes.AnalyticsEventSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types2.AnalyticsResult](), runtimeserde.GetSerdeType[*types2.AnalyticsResult]():
		{
			var serde runtimeserde.Serde[*types2.AnalyticsResult] = &serdes.AnalyticsResultSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types.OrderProcessed](), runtimeserde.GetSerdeType[*types.OrderProcessed]():
		{
			var serde runtimeserde.Serde[*types.OrderProcessed] = &serdes2.OrderProcessedSerde{}
			return serde, nil
		}

	}
	return nil, nil
}

func (s *Service) RegisterHTTPHandler(path string, handler http.Handler) {
	if s.httpMux != nil {
		s.httpMux.Handle(path, s.httpHandlerMiddleware(path, handler))
	} else {
		s.ServiceApp.RegisterHTTPHandler(path, s.httpHandlerMiddleware(path, handler))
	}
}

func (s *Service) Config() *config.Config {
	return s.ServiceApp.GetConfig().(*config.Config)
}

func (s *Service) initMakers(ctx context.Context) error {
	if s.makers.analyticsCountOrderProcessedMaker == nil {
		s.makers.analyticsCountOrderProcessedMaker = func(ctx context.Context, cfg *runtimecfg.ProcessStreamConfig, env environment.ServiceEnvironment) (*analytics.CountOrderProcessed, error) {
			return analytics.MakeCountOrderProcessed(ctx, env, cfg)
		}
	}
	if s.makers.joinanalyticsKeyOrdersForJoinMaker == nil {
		s.makers.joinanalyticsKeyOrdersForJoinMaker = func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*joinanalytics.KeyOrdersForJoin, error) {
			return joinanalytics.MakeKeyOrdersForJoin(ctx, env, cfg)
		}
	}
	if s.makers.multijoinanalyticsKeyOrdersForMultiJoinMaker == nil {
		s.makers.multijoinanalyticsKeyOrdersForMultiJoinMaker = func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.KeyOrdersForMultiJoin, error) {
			return multijoinanalytics.MakeKeyOrdersForMultiJoin(ctx, env, cfg)
		}
	}
	if s.makers.joinanalyticsKeyPaymentsForJoinMaker == nil {
		s.makers.joinanalyticsKeyPaymentsForJoinMaker = func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*joinanalytics.KeyPaymentsForJoin, error) {
			return joinanalytics.MakeKeyPaymentsForJoin(ctx, env, cfg)
		}
	}
	if s.makers.joinanalyticsJoinOrderPaymentAnalyticsMaker == nil {
		s.makers.joinanalyticsJoinOrderPaymentAnalyticsMaker = func(ctx context.Context, cfg *runtimecfg.JoinStreamConfig, env environment.ServiceEnvironment) (*joinanalytics.JoinOrderPaymentAnalytics, error) {
			return joinanalytics.MakeJoinOrderPaymentAnalytics(ctx, env, cfg)
		}
	}
	if s.makers.multijoinanalyticsKeyPaymentsForMultiJoinMaker == nil {
		s.makers.multijoinanalyticsKeyPaymentsForMultiJoinMaker = func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.KeyPaymentsForMultiJoin, error) {
			return multijoinanalytics.MakeKeyPaymentsForMultiJoin(ctx, env, cfg)
		}
	}
	if s.makers.multijoinanalyticsKeyShipmentsForMultiJoinMaker == nil {
		s.makers.multijoinanalyticsKeyShipmentsForMultiJoinMaker = func(ctx context.Context, cfg *runtimecfg.KeyByStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.KeyShipmentsForMultiJoin, error) {
			return multijoinanalytics.MakeKeyShipmentsForMultiJoin(ctx, env, cfg)
		}
	}
	if s.makers.multijoinanalyticsMultiJoinAnalyticsEventsMaker == nil {
		s.makers.multijoinanalyticsMultiJoinAnalyticsEventsMaker = func(ctx context.Context, cfg *runtimecfg.MultiJoinStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.MultiJoinAnalyticsEvents, error) {
			return multijoinanalytics.MakeMultiJoinAnalyticsEvents(ctx, env, cfg)
		}
	}
	if s.makers.multijoinanalyticsRouteAnalyticsResultMaker == nil {
		s.makers.multijoinanalyticsRouteAnalyticsResultMaker = func(ctx context.Context, cfg *runtimecfg.CaseStreamConfig, env environment.ServiceEnvironment) (*multijoinanalytics.RouteAnalyticsResult, error) {
			return multijoinanalytics.MakeRouteAnalyticsResult(ctx, env, cfg)
		}
	}
	if s.makers.cronAnalyticsScheduleSourceMaker == nil {
		s.makers.cronAnalyticsScheduleSourceMaker = func(ctx context.Context, cfg *runtimecfg.CronEndpointConfig, env environment.ServiceEnvironment) (*cron.AnalyticsScheduleSource, error) {
			return cron.MakeAnalyticsScheduleSource(ctx, env, cfg)
		}
	}
	if s.makers.endpointOrderProcessedEndpointSourceMaker == nil {
		s.makers.endpointOrderProcessedEndpointSourceMaker = func(ctx context.Context, cfg *runtimecfg.KafkaEndpointConfig, env environment.ServiceEnvironment) (*endpoint.OrderProcessedEndpointSource, error) {
			return endpoint.MakeOrderProcessedEndpointSource(ctx, env, cfg)
		}
	}
	if s.makers.endpointAnalyticsOrdersSourceMaker == nil {
		s.makers.endpointAnalyticsOrdersSourceMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.AnalyticsOrdersSource, error) {
			return endpoint.MakeAnalyticsOrdersSource(ctx, env, cfg)
		}
	}
	if s.makers.endpointAnalyticsPaymentsSourceMaker == nil {
		s.makers.endpointAnalyticsPaymentsSourceMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.AnalyticsPaymentsSource, error) {
			return endpoint.MakeAnalyticsPaymentsSource(ctx, env, cfg)
		}
	}
	if s.makers.endpointAnalyticsShipmentsSourceMaker == nil {
		s.makers.endpointAnalyticsShipmentsSourceMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.AnalyticsShipmentsSource, error) {
			return endpoint.MakeAnalyticsShipmentsSource(ctx, env, cfg)
		}
	}
	if s.makers.endpointJoinedAnalyticsSinkMaker == nil {
		s.makers.endpointJoinedAnalyticsSinkMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.JoinedAnalyticsSink, error) {
			return endpoint.MakeJoinedAnalyticsSink(ctx, env, cfg)
		}
	}
	if s.makers.endpointHighValueAnalyticsSinkMaker == nil {
		s.makers.endpointHighValueAnalyticsSinkMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.HighValueAnalyticsSink, error) {
			return endpoint.MakeHighValueAnalyticsSink(ctx, env, cfg)
		}
	}
	if s.makers.endpointStandardAnalyticsSinkMaker == nil {
		s.makers.endpointStandardAnalyticsSinkMaker = func(ctx context.Context, cfg *runtimecfg.CustomEndpointConfig, env environment.ServiceEnvironment) (*endpoint.StandardAnalyticsSink, error) {
			return endpoint.MakeStandardAnalyticsSink(ctx, env, cfg)
		}
	}

	return nil
}

func (s *Service) buildRuntime(ctx context.Context) error {
	cfg := s.Config()

	if err := s.initMakers(ctx); err != nil {
		return fmt.Errorf("init makers failed: %w", err)
	}

	if err := s.customMakersInit(ctx); err != nil {
		return fmt.Errorf("custom init makers failed: %w", err)
	}

	var err error

	if s.httpMuxMaker != nil {
		if s.httpMux, err = s.httpMuxMaker(ctx, s); err != nil {
			return fmt.Errorf("create http mux failed: %w", err)
		}
	}

	if err := s.initFunctions(ctx, cfg, s); err != nil {
		return fmt.Errorf("init functions failed: %w", err)
	}

	if err := s.customFunctionsInit(ctx); err != nil {
		return fmt.Errorf("custom functions init failed: %w", err)
	}

	if err := s.initStreams(ctx, cfg, s); err != nil {
		return fmt.Errorf("init streams failed: %w", err)
	}

	return nil
}

func (s *Service) initStreams(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment) error {
	var err error
	if s.streams.analyticsSchedule, err = transformation.Input[string, any, error](&cfg.Streams.AnalyticsSchedule, env); err != nil {
		return err
	}
	if s.streams.consumeOrderProcessed, err = transformation.Input[*types.OrderProcessed, *types.OrderProcessed, error](&cfg.Streams.ConsumeOrderProcessed, env); err != nil {
		return err
	}
	if s.streams.countOrderProcessed, err = transformation.Process[*types.OrderProcessed, *types.OrderProcessed, error](&cfg.Streams.CountOrderProcessed, s.streams.consumeOrderProcessed, s.functions.analyticsCountOrderProcessed); err != nil {
		return err
	}
	if s.streams.analyticsOrders, err = transformation.Input[*types2.AnalyticsEvent, any, error](&cfg.Streams.AnalyticsOrders, env); err != nil {
		return err
	}
	if s.streams.splitAnalyticsOrders, err = transformation.Split[*types2.AnalyticsEvent](&cfg.Streams.SplitAnalyticsOrders, s.streams.analyticsOrders); err != nil {
		return err
	}
	if s.streams.keyOrdersForJoin, err = transformation.KeyBy[*types2.AnalyticsEvent, string, *types2.AnalyticsEvent](&cfg.Streams.KeyOrdersForJoin, s.streams.splitAnalyticsOrders.AddStream(), s.functions.joinanalyticsKeyOrdersForJoin); err != nil {
		return err
	}
	if s.streams.keyOrdersForMultiJoin, err = transformation.KeyBy[*types2.AnalyticsEvent, string, *types2.AnalyticsEvent](&cfg.Streams.KeyOrdersForMultiJoin, s.streams.splitAnalyticsOrders.AddStream(), s.functions.multijoinanalyticsKeyOrdersForMultiJoin); err != nil {
		return err
	}
	if s.streams.analyticsPayments, err = transformation.Input[*types2.AnalyticsEvent, any, error](&cfg.Streams.AnalyticsPayments, env); err != nil {
		return err
	}
	if s.streams.splitAnalyticsPayments, err = transformation.Split[*types2.AnalyticsEvent](&cfg.Streams.SplitAnalyticsPayments, s.streams.analyticsPayments); err != nil {
		return err
	}
	if s.streams.keyPaymentsForJoin, err = transformation.KeyBy[*types2.AnalyticsEvent, string, *types2.AnalyticsEvent](&cfg.Streams.KeyPaymentsForJoin, s.streams.splitAnalyticsPayments.AddStream(), s.functions.joinanalyticsKeyPaymentsForJoin); err != nil {
		return err
	}
	if s.streams.joinOrderPaymentAnalytics, err = transformation.Join[string, *types2.AnalyticsEvent, *types2.AnalyticsEvent, *types2.AnalyticsResult](&cfg.Streams.JoinOrderPaymentAnalytics, s.streams.keyOrdersForJoin, s.streams.keyPaymentsForJoin, s.functions.joinanalyticsJoinOrderPaymentAnalytics); err != nil {
		return err
	}
	if s.streams.writeJoinedAnalytics, err = transformation.Sink[*types2.AnalyticsResult, error](&cfg.Streams.WriteJoinedAnalytics, s.streams.joinOrderPaymentAnalytics); err != nil {
		return err
	}
	if s.streams.keyPaymentsForMultiJoin, err = transformation.KeyBy[*types2.AnalyticsEvent, string, *types2.AnalyticsEvent](&cfg.Streams.KeyPaymentsForMultiJoin, s.streams.splitAnalyticsPayments.AddStream(), s.functions.multijoinanalyticsKeyPaymentsForMultiJoin); err != nil {
		return err
	}
	if s.streams.analyticsShipments, err = transformation.Input[*types2.AnalyticsEvent, any, error](&cfg.Streams.AnalyticsShipments, env); err != nil {
		return err
	}
	if s.streams.keyShipmentsForMultiJoin, err = transformation.KeyBy[*types2.AnalyticsEvent, string, *types2.AnalyticsEvent](&cfg.Streams.KeyShipmentsForMultiJoin, s.streams.analyticsShipments, s.functions.multijoinanalyticsKeyShipmentsForMultiJoin); err != nil {
		return err
	}
	if s.streams.multiJoinAnalyticsEvents, err = transformation.MultiJoin[string, *types2.AnalyticsEvent, *types2.AnalyticsResult](&cfg.Streams.MultiJoinAnalyticsEvents, s.streams.keyOrdersForMultiJoin, s.functions.multijoinanalyticsMultiJoinAnalyticsEvents); err != nil {
		return err
	}
	if err = transformation.MultiJoinLink[string, *types2.AnalyticsEvent, *types2.AnalyticsEvent, *types2.AnalyticsResult](s.streams.multiJoinAnalyticsEvents, s.streams.keyPaymentsForMultiJoin); err != nil {
		return err
	}
	if err = transformation.MultiJoinLink[string, *types2.AnalyticsEvent, *types2.AnalyticsEvent, *types2.AnalyticsResult](s.streams.multiJoinAnalyticsEvents, s.streams.keyShipmentsForMultiJoin); err != nil {
		return err
	}
	if s.streams.routeAnalyticsResult, err = transformation.CaseStream[*types2.AnalyticsResult](&cfg.Streams.RouteAnalyticsResult, s.streams.multiJoinAnalyticsEvents, s.functions.multijoinanalyticsRouteAnalyticsResult); err != nil {
		return err
	}
	if s.streams.highValueAnalytics, err = transformation.WhenStream[*types2.AnalyticsResult, *types2.AnalyticsResult](&cfg.Streams.HighValueAnalytics, s.streams.routeAnalyticsResult); err != nil {
		return err
	}
	if s.streams.writeHighValueAnalytics, err = transformation.Sink[*types2.AnalyticsResult, error](&cfg.Streams.WriteHighValueAnalytics, s.streams.highValueAnalytics); err != nil {
		return err
	}
	if s.streams.standardAnalytics, err = transformation.WhenStream[*types2.AnalyticsResult, *types2.AnalyticsResult](&cfg.Streams.StandardAnalytics, s.streams.routeAnalyticsResult); err != nil {
		return err
	}
	if s.streams.writeStandardAnalytics, err = transformation.Sink[*types2.AnalyticsResult, error](&cfg.Streams.WriteStandardAnalytics, s.streams.standardAnalytics); err != nil {
		return err
	}
	if err = s.streams.consumeOrderProcessed.SetSource(s.streams.countOrderProcessed); err != nil {
		return err
	}
	if s.dataConnectors.analyticsSchedule, err = cron.MakeEndpointConsumerAnalyticsScheduleSource(s.streams.analyticsSchedule, s.functions.cronAnalyticsScheduleSource); err != nil {
		return err
	}
	if s.dataConnectors.orderProcessed, err = endpoint.MakeEndpointConsumerOrderProcessedEndpointSource(s.streams.consumeOrderProcessed, s.functions.endpointOrderProcessedEndpointSource); err != nil {
		return err
	}
	if s.dataConnectors.analyticsOrders, err = endpoint.MakeEndpointConsumerAnalyticsOrdersSource(s.streams.analyticsOrders, s.functions.endpointAnalyticsOrdersSource); err != nil {
		return err
	}
	if s.dataConnectors.analyticsPayments, err = endpoint.MakeEndpointConsumerAnalyticsPaymentsSource(s.streams.analyticsPayments, s.functions.endpointAnalyticsPaymentsSource); err != nil {
		return err
	}
	if s.dataConnectors.analyticsShipments, err = endpoint.MakeEndpointConsumerAnalyticsShipmentsSource(s.streams.analyticsShipments, s.functions.endpointAnalyticsShipmentsSource); err != nil {
		return err
	}
	if s.dataConnectors.writeJoinedAnalyticsJoinedAnalytics, err = endpoint.MakeEndpointConsumerJoinedAnalyticsSink(s.streams.writeJoinedAnalytics, s.functions.endpointJoinedAnalyticsSink); err != nil {
		return err
	}
	if s.dataConnectors.writeHighValueAnalyticsHighValueAnalytics, err = endpoint.MakeEndpointConsumerHighValueAnalyticsSink(s.streams.writeHighValueAnalytics, s.functions.endpointHighValueAnalyticsSink); err != nil {
		return err
	}
	if s.dataConnectors.writeStandardAnalyticsStandardAnalytics, err = endpoint.MakeEndpointConsumerStandardAnalyticsSink(s.streams.writeStandardAnalytics, s.functions.endpointStandardAnalyticsSink); err != nil {
		return err
	}
	_ = err
	_ = cfg
	return nil
}

func (s *Service) initFunctions(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment) error {
	eg, egCtx := errgroup.WithContext(ctx)
	if s.makers.analyticsCountOrderProcessedMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.analyticsCountOrderProcessed, err = s.makers.analyticsCountOrderProcessedMaker(egCtx, &cfg.Streams.CountOrderProcessed, env)
			return err
		})
	}
	if s.makers.joinanalyticsKeyOrdersForJoinMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.joinanalyticsKeyOrdersForJoin, err = s.makers.joinanalyticsKeyOrdersForJoinMaker(egCtx, &cfg.Streams.KeyOrdersForJoin, env)
			return err
		})
	}
	if s.makers.multijoinanalyticsKeyOrdersForMultiJoinMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.multijoinanalyticsKeyOrdersForMultiJoin, err = s.makers.multijoinanalyticsKeyOrdersForMultiJoinMaker(egCtx, &cfg.Streams.KeyOrdersForMultiJoin, env)
			return err
		})
	}
	if s.makers.joinanalyticsKeyPaymentsForJoinMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.joinanalyticsKeyPaymentsForJoin, err = s.makers.joinanalyticsKeyPaymentsForJoinMaker(egCtx, &cfg.Streams.KeyPaymentsForJoin, env)
			return err
		})
	}
	if s.makers.joinanalyticsJoinOrderPaymentAnalyticsMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.joinanalyticsJoinOrderPaymentAnalytics, err = s.makers.joinanalyticsJoinOrderPaymentAnalyticsMaker(egCtx, &cfg.Streams.JoinOrderPaymentAnalytics, env)
			return err
		})
	}
	if s.makers.multijoinanalyticsKeyPaymentsForMultiJoinMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.multijoinanalyticsKeyPaymentsForMultiJoin, err = s.makers.multijoinanalyticsKeyPaymentsForMultiJoinMaker(egCtx, &cfg.Streams.KeyPaymentsForMultiJoin, env)
			return err
		})
	}
	if s.makers.multijoinanalyticsKeyShipmentsForMultiJoinMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.multijoinanalyticsKeyShipmentsForMultiJoin, err = s.makers.multijoinanalyticsKeyShipmentsForMultiJoinMaker(egCtx, &cfg.Streams.KeyShipmentsForMultiJoin, env)
			return err
		})
	}
	if s.makers.multijoinanalyticsMultiJoinAnalyticsEventsMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.multijoinanalyticsMultiJoinAnalyticsEvents, err = s.makers.multijoinanalyticsMultiJoinAnalyticsEventsMaker(egCtx, &cfg.Streams.MultiJoinAnalyticsEvents, env)
			return err
		})
	}
	if s.makers.multijoinanalyticsRouteAnalyticsResultMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.multijoinanalyticsRouteAnalyticsResult, err = s.makers.multijoinanalyticsRouteAnalyticsResultMaker(egCtx, &cfg.Streams.RouteAnalyticsResult, env)
			return err
		})
	}
	if s.makers.cronAnalyticsScheduleSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.cronAnalyticsScheduleSource, err = s.makers.cronAnalyticsScheduleSourceMaker(egCtx, &cfg.Endpoints.AnalyticsSchedule, env)
			return err
		})
	}
	if s.makers.endpointOrderProcessedEndpointSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointOrderProcessedEndpointSource, err = s.makers.endpointOrderProcessedEndpointSourceMaker(egCtx, &cfg.Endpoints.OrderProcessed, env)
			return err
		})
	}
	if s.makers.endpointAnalyticsOrdersSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointAnalyticsOrdersSource, err = s.makers.endpointAnalyticsOrdersSourceMaker(egCtx, &cfg.Endpoints.AnalyticsOrders, env)
			return err
		})
	}
	if s.makers.endpointAnalyticsPaymentsSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointAnalyticsPaymentsSource, err = s.makers.endpointAnalyticsPaymentsSourceMaker(egCtx, &cfg.Endpoints.AnalyticsPayments, env)
			return err
		})
	}
	if s.makers.endpointAnalyticsShipmentsSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointAnalyticsShipmentsSource, err = s.makers.endpointAnalyticsShipmentsSourceMaker(egCtx, &cfg.Endpoints.AnalyticsShipments, env)
			return err
		})
	}
	if s.makers.endpointJoinedAnalyticsSinkMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointJoinedAnalyticsSink, err = s.makers.endpointJoinedAnalyticsSinkMaker(egCtx, &cfg.Endpoints.JoinedAnalytics, env)
			return err
		})
	}
	if s.makers.endpointHighValueAnalyticsSinkMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointHighValueAnalyticsSink, err = s.makers.endpointHighValueAnalyticsSinkMaker(egCtx, &cfg.Endpoints.HighValueAnalytics, env)
			return err
		})
	}
	if s.makers.endpointStandardAnalyticsSinkMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointStandardAnalyticsSink, err = s.makers.endpointStandardAnalyticsSinkMaker(egCtx, &cfg.Endpoints.StandardAnalytics, env)
			return err
		})
	}
	if err := eg.Wait(); err != nil {
		return err
	}
	return nil
}

func (s *Service) ServiceInit() error {
	return nil
}

func (s *Service) StartService(ctx context.Context) error {

	if err := s.buildRuntime(ctx); err != nil {
		return fmt.Errorf("build runtime failed: %w", err)
	}

	if err := s.start(ctx); err != nil {
		return fmt.Errorf("service start failed: %w", err)
	}

	if err := s.ServiceApp.Start(ctx); err != nil {
		return fmt.Errorf("service app start failed: %w", err)
	}

	var err error

	if s.httpMux != nil {
		if s.httpServerMaker != nil {
			if s.httpServer, err = s.httpServerMaker(ctx, s); err != nil {
				return fmt.Errorf("create http server failed: %w", err)
			}
		}
	}
	if s.httpServer != nil {
		s.httpServerDone = make(chan struct{})
		ln, err := net.Listen("tcp", s.httpServer.Addr)
		if err != nil {
			return fmt.Errorf("failed to listen http port: %v", err)
		}
		go func() {
			s.Log().Info(ctx, "HTTP server listening", log.Any("addr", s.httpServer.Addr))
			if err := s.httpServer.Serve(ln); err != nil && !errors.Is(err, http.ErrServerClosed) {
				s.Log().Error(ctx, "HTTP server stopped unexpectedly", log.Err(err))
			}
			close(s.httpServerDone)
		}()
	}
	return nil
}

func (s *Service) StopService(ctx context.Context) {
	svcCfg := s.ServiceConfig()
	timeoutCtx, cancel := context.WithTimeout(ctx, time.Duration(svcCfg.ShutdownTimeout)*time.Millisecond)
	defer cancel()

	// First stop transport admission and let requests already accepted by the
	// HTTP/gRPC servers finish while the graph runtime and outbound clients
	// are still available to their handlers.
	wg := sync.WaitGroup{}
	admissionDone := make(chan struct{})
	if s.httpServer != nil {
		wg.Add(1)
		go func() {
			defer wg.Done()
			if err := s.httpServer.Shutdown(timeoutCtx); err != nil {
				s.Log().Warn(timeoutCtx, "HTTP server shutdown", log.Err(err))
			}
			<-s.httpServerDone
		}()
	}
	go func() {
		wg.Wait()
		close(admissionDone)
	}()
	select {
	case <-admissionDone:
	case <-timeoutCtx.Done():
		s.Log().Warn(timeoutCtx, "transport drain timed out", log.Err(timeoutCtx.Err()))
	}

	// Only after inbound handlers have drained may graph resources, pools and
	// sinks stop. All phases share the same absolute shutdown deadline.
	runtimeDone := make(chan struct{})
	go func() {
		defer close(runtimeDone)
		s.ServiceApp.Stop(timeoutCtx)
	}()
	select {
	case <-runtimeDone:
	case <-timeoutCtx.Done():
		s.Log().Warn(timeoutCtx, "graph runtime stop timed out", log.Err(timeoutCtx.Err()))
	}

	// Outbound clients and user-owned resources are last: accepted handlers
	// and graph shutdown callbacks may still need them in earlier phases.
	cleanupWg := sync.WaitGroup{}

	cleanupWg.Add(1)
	go func() {
		defer cleanupWg.Done()
		s.stop(timeoutCtx)
	}()
	cleanupDone := make(chan struct{})
	go func() {
		cleanupWg.Wait()
		close(cleanupDone)
	}()
	select {
	case <-cleanupDone:
	case <-timeoutCtx.Done():
		s.Log().Warn(timeoutCtx, "service cleanup timed out", log.Err(timeoutCtx.Err()))
	}
}

func Start(ctx context.Context,
	dependency environment.ServiceDependencies,
	done <-chan struct{},
	configPath *string,
	valuesPath *string,
	version string,
	commit string,
) error {
	if dependency == nil {
		dependency = &serviceDependencies{}
	}

	service, err := runtime.MakeService[*Service,
		*config.Config](
		ctx,
		"Analytics Service",
		dependency,
		configPath,
		valuesPath,
		func() *Service { return &Service{} },
		func() *config.Config { return config.MakeConfig() },
	)
	if err != nil {
		return fmt.Errorf("service start failed: %w", err)
	}
	defer service.Release()

	service.Log().Info(ctx, "starting service", log.Str("service", service.ServiceConfig().Name), log.Str("version", version), log.Str("commit", commit))

	var stop chan os.Signal
	if done == nil {
		stop = make(chan os.Signal, 2)
		signal.Notify(stop, syscall.SIGINT)
		signal.Notify(stop, syscall.SIGTERM)
	}

	if ctx == nil {
		localCtx, cancel := context.WithCancel(context.Background())
		defer cancel()

		ctx = localCtx
	}

	if err = service.StartService(ctx); err != nil {
		return fmt.Errorf("start service failed: %w", err)
	}
	service.Log().Info(ctx, "service started", log.Str("service", service.ServiceConfig().Name))

	if os.Getenv("GORUNDEBUG_TEST") != "" && stop != nil {
		time.AfterFunc(1*time.Second, func() {
			close(stop)
		})
	}
	if stop != nil {
		<-stop
	} else if done != nil {
		<-done
	}
	service.Log().Info(ctx, "service stop signal received", log.Str("service", service.ServiceConfig().Name))
	service.StopService(context.WithoutCancel(ctx))
	service.Log().Info(ctx, "service stopped", log.Str("service", service.ServiceConfig().Name))
	return nil
}
