// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	config "github.com/gorundebug/analyticsservice/internal/config"
	types "github.com/gorundebug/analyticsservice/internal/types"
	types2 "github.com/gorundebug/model_go/pkg/types"
	"github.com/gorundebug/servicelib/runtime"
	"github.com/gorundebug/servicelib/runtime/datastruct"
	"github.com/gorundebug/servicelib/transformation"
)

type serviceStreams struct {
	cycleAnalyticsLink            runtime.TypedLinkStream[*types.AnalyticsEvent]
	analyticsSchedule             runtime.TypedInputStream[string, any, error]
	consumeOrderProcessed         runtime.TypedInputStream[*types2.OrderProcessed, *types2.OrderProcessed, error]
	countOrderProcessed           runtime.TypedProcessConsumedStream[*types2.OrderProcessed, *types2.OrderProcessed, error]
	analyticsOrders               runtime.TypedInputStream[*types.AnalyticsEvent, any, error]
	splitAnalyticsOrders          runtime.TypedSplitStream[*types.AnalyticsEvent]
	keyOrdersForJoin              runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, datastruct.KeyValue[string, *types.AnalyticsEvent]]
	keyOrdersForMultiJoin         runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, datastruct.KeyValue[string, *types.AnalyticsEvent]]
	analyticsPayments             runtime.TypedInputStream[*types.AnalyticsEvent, any, error]
	splitAnalyticsPayments        runtime.TypedSplitStream[*types.AnalyticsEvent]
	keyPaymentsForJoin            runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, datastruct.KeyValue[string, *types.AnalyticsEvent]]
	joinOrderPaymentAnalytics     runtime.TypedJoinConsumedStream[string, *types.AnalyticsEvent, *types.AnalyticsEvent, *types.AnalyticsResult]
	writeJoinedAnalytics          runtime.TypedSinkStream[*types.AnalyticsResult, error]
	keyPaymentsForMultiJoin       runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, datastruct.KeyValue[string, *types.AnalyticsEvent]]
	analyticsShipments            runtime.TypedInputStream[*types.AnalyticsEvent, any, error]
	keyShipmentsForMultiJoin      runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, datastruct.KeyValue[string, *types.AnalyticsEvent]]
	multiJoinAnalyticsEvents      runtime.TypedMultiJoinConsumedStream[string, *types.AnalyticsEvent, *types.AnalyticsResult]
	routeAnalyticsResult          runtime.TypedCaseStream[*types.AnalyticsResult]
	highValueAnalytics            runtime.TypedConsumedStream[*types.AnalyticsResult]
	writeHighValueAnalytics       runtime.TypedSinkStream[*types.AnalyticsResult, error]
	standardAnalytics             runtime.TypedConsumedStream[*types.AnalyticsResult]
	writeStandardAnalytics        runtime.TypedSinkStream[*types.AnalyticsResult, error]
	cycleAnalyticsInput           runtime.TypedInputStream[*types.AnalyticsEvent, any, error]
	mergeCycleAnalytics           runtime.TypedConsumedStream[*types.AnalyticsEvent]
	advanceCycleAnalytics         runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, *types.AnalyticsEvent]
	splitCycleAnalytics           runtime.TypedSplitStream[*types.AnalyticsEvent]
	completeCycleAnalytics        runtime.TypedConsumedStream[*types.AnalyticsEvent]
	writeCycleAnalytics           runtime.TypedSinkStream[*types.AnalyticsEvent, error]
	continueCycleAnalytics        runtime.TypedConsumedStream[*types.AnalyticsEvent]
	analyzeAnalyticsSubstream     runtime.TypedSubStream[*types.AnalyticsEvent, *types.AnalyticsResult]
	buildSubstreamAnalyticsResult runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, *types.AnalyticsResult]
	substreamAnalyticsInput       runtime.TypedInputStream[*types.AnalyticsEvent, any, error]
	invokeAnalyticsSubstream      runtime.TypedTransformConsumedStream[*types.AnalyticsEvent, *types.AnalyticsResult]
	writeSubstreamAnalytics       runtime.TypedSinkStream[*types.AnalyticsResult, error]
}

// initStreams preserves the global topological order, including cross-pipeline links.
func (streams *serviceStreams) initStreams(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment, functions *serviceFunctions) error {
	var err error

	if streams.cycleAnalyticsLink, err = transformation.Link[*types.AnalyticsEvent](&cfg.Streams.CycleAnalyticsLink, env); err != nil {
		return err
	}
	if streams.analyticsSchedule, err = transformation.Input[string, any, error](&cfg.Streams.AnalyticsSchedule, env); err != nil {
		return err
	}
	if streams.consumeOrderProcessed, err = transformation.Input[*types2.OrderProcessed, *types2.OrderProcessed, error](&cfg.Streams.ConsumeOrderProcessed, env); err != nil {
		return err
	}
	if streams.countOrderProcessed, err = transformation.Process[*types2.OrderProcessed, *types2.OrderProcessed, error](&cfg.Streams.CountOrderProcessed, streams.consumeOrderProcessed, functions.analyticsCountOrderProcessed); err != nil {
		return err
	}
	if streams.analyticsOrders, err = transformation.Input[*types.AnalyticsEvent, any, error](&cfg.Streams.AnalyticsOrders, env); err != nil {
		return err
	}
	if streams.splitAnalyticsOrders, err = transformation.Split[*types.AnalyticsEvent](&cfg.Streams.SplitAnalyticsOrders, streams.analyticsOrders); err != nil {
		return err
	}
	if streams.keyOrdersForJoin, err = transformation.KeyBy[*types.AnalyticsEvent, string, *types.AnalyticsEvent](&cfg.Streams.KeyOrdersForJoin, streams.splitAnalyticsOrders.AddStream(), functions.joinanalyticsKeyOrdersForJoin); err != nil {
		return err
	}
	if streams.keyOrdersForMultiJoin, err = transformation.KeyBy[*types.AnalyticsEvent, string, *types.AnalyticsEvent](&cfg.Streams.KeyOrdersForMultiJoin, streams.splitAnalyticsOrders.AddStream(), functions.multijoinanalyticsKeyOrdersForMultiJoin); err != nil {
		return err
	}
	if streams.analyticsPayments, err = transformation.Input[*types.AnalyticsEvent, any, error](&cfg.Streams.AnalyticsPayments, env); err != nil {
		return err
	}
	if streams.splitAnalyticsPayments, err = transformation.Split[*types.AnalyticsEvent](&cfg.Streams.SplitAnalyticsPayments, streams.analyticsPayments); err != nil {
		return err
	}
	if streams.keyPaymentsForJoin, err = transformation.KeyBy[*types.AnalyticsEvent, string, *types.AnalyticsEvent](&cfg.Streams.KeyPaymentsForJoin, streams.splitAnalyticsPayments.AddStream(), functions.joinanalyticsKeyPaymentsForJoin); err != nil {
		return err
	}
	if streams.joinOrderPaymentAnalytics, err = transformation.Join[string, *types.AnalyticsEvent, *types.AnalyticsEvent, *types.AnalyticsResult](&cfg.Streams.JoinOrderPaymentAnalytics, streams.keyOrdersForJoin, streams.keyPaymentsForJoin, functions.joinanalyticsJoinOrderPaymentAnalytics); err != nil {
		return err
	}
	if streams.writeJoinedAnalytics, err = transformation.Sink[*types.AnalyticsResult, error](&cfg.Streams.WriteJoinedAnalytics, streams.joinOrderPaymentAnalytics); err != nil {
		return err
	}
	if streams.keyPaymentsForMultiJoin, err = transformation.KeyBy[*types.AnalyticsEvent, string, *types.AnalyticsEvent](&cfg.Streams.KeyPaymentsForMultiJoin, streams.splitAnalyticsPayments.AddStream(), functions.multijoinanalyticsKeyPaymentsForMultiJoin); err != nil {
		return err
	}
	if streams.analyticsShipments, err = transformation.Input[*types.AnalyticsEvent, any, error](&cfg.Streams.AnalyticsShipments, env); err != nil {
		return err
	}
	if streams.keyShipmentsForMultiJoin, err = transformation.KeyBy[*types.AnalyticsEvent, string, *types.AnalyticsEvent](&cfg.Streams.KeyShipmentsForMultiJoin, streams.analyticsShipments, functions.multijoinanalyticsKeyShipmentsForMultiJoin); err != nil {
		return err
	}
	if streams.multiJoinAnalyticsEvents, err = transformation.MultiJoin[string, *types.AnalyticsEvent, *types.AnalyticsResult](&cfg.Streams.MultiJoinAnalyticsEvents, streams.keyOrdersForMultiJoin, functions.multijoinanalyticsMultiJoinAnalyticsEvents); err != nil {
		return err
	}
	if err = transformation.MultiJoinLink[string, *types.AnalyticsEvent, *types.AnalyticsEvent, *types.AnalyticsResult](streams.multiJoinAnalyticsEvents, streams.keyPaymentsForMultiJoin); err != nil {
		return err
	}
	if err = transformation.MultiJoinLink[string, *types.AnalyticsEvent, *types.AnalyticsEvent, *types.AnalyticsResult](streams.multiJoinAnalyticsEvents, streams.keyShipmentsForMultiJoin); err != nil {
		return err
	}
	if streams.routeAnalyticsResult, err = transformation.CaseStream[*types.AnalyticsResult](&cfg.Streams.RouteAnalyticsResult, streams.multiJoinAnalyticsEvents, functions.multijoinanalyticsRouteAnalyticsResult); err != nil {
		return err
	}
	if streams.highValueAnalytics, err = transformation.WhenStream[*types.AnalyticsResult, *types.AnalyticsResult](&cfg.Streams.HighValueAnalytics, streams.routeAnalyticsResult); err != nil {
		return err
	}
	if streams.writeHighValueAnalytics, err = transformation.Sink[*types.AnalyticsResult, error](&cfg.Streams.WriteHighValueAnalytics, streams.highValueAnalytics); err != nil {
		return err
	}
	if streams.standardAnalytics, err = transformation.WhenStream[*types.AnalyticsResult, *types.AnalyticsResult](&cfg.Streams.StandardAnalytics, streams.routeAnalyticsResult); err != nil {
		return err
	}
	if streams.writeStandardAnalytics, err = transformation.Sink[*types.AnalyticsResult, error](&cfg.Streams.WriteStandardAnalytics, streams.standardAnalytics); err != nil {
		return err
	}
	if streams.cycleAnalyticsInput, err = transformation.Input[*types.AnalyticsEvent, any, error](&cfg.Streams.CycleAnalyticsInput, env); err != nil {
		return err
	}
	if streams.mergeCycleAnalytics, err = transformation.Merge[*types.AnalyticsEvent](&cfg.Streams.MergeCycleAnalytics, streams.cycleAnalyticsInput, streams.cycleAnalyticsLink); err != nil {
		return err
	}
	if streams.advanceCycleAnalytics, err = transformation.Map[*types.AnalyticsEvent, *types.AnalyticsEvent](&cfg.Streams.AdvanceCycleAnalytics, streams.mergeCycleAnalytics, functions.cycleanalyticsAdvanceCycleAnalytics); err != nil {
		return err
	}
	if streams.splitCycleAnalytics, err = transformation.Split[*types.AnalyticsEvent](&cfg.Streams.SplitCycleAnalytics, streams.advanceCycleAnalytics); err != nil {
		return err
	}
	if streams.completeCycleAnalytics, err = transformation.Filter[*types.AnalyticsEvent](&cfg.Streams.CompleteCycleAnalytics, streams.splitCycleAnalytics.AddStream(), functions.cycleanalyticsCompleteCycleAnalytics); err != nil {
		return err
	}
	if streams.writeCycleAnalytics, err = transformation.Sink[*types.AnalyticsEvent, error](&cfg.Streams.WriteCycleAnalytics, streams.completeCycleAnalytics); err != nil {
		return err
	}
	if streams.continueCycleAnalytics, err = transformation.Filter[*types.AnalyticsEvent](&cfg.Streams.ContinueCycleAnalytics, streams.splitCycleAnalytics.AddStream(), functions.cycleanalyticsContinueCycleAnalytics); err != nil {
		return err
	}
	if streams.analyzeAnalyticsSubstream, err = transformation.SubStream[*types.AnalyticsEvent, *types.AnalyticsResult](&cfg.Streams.AnalyzeAnalyticsSubstream, env); err != nil {
		return err
	}
	if streams.buildSubstreamAnalyticsResult, err = transformation.Map[*types.AnalyticsEvent, *types.AnalyticsResult](&cfg.Streams.BuildSubstreamAnalyticsResult, streams.analyzeAnalyticsSubstream, functions.substreamanalyticsBuildSubstreamAnalyticsResult); err != nil {
		return err
	}
	if streams.substreamAnalyticsInput, err = transformation.Input[*types.AnalyticsEvent, any, error](&cfg.Streams.SubstreamAnalyticsInput, env); err != nil {
		return err
	}
	if streams.invokeAnalyticsSubstream, err = transformation.Map[*types.AnalyticsEvent, *types.AnalyticsResult](&cfg.Streams.InvokeAnalyticsSubstream, streams.substreamAnalyticsInput, functions.substreamanalyticsInvokeAnalyticsSubstream); err != nil {
		return err
	}
	if streams.writeSubstreamAnalytics, err = transformation.Sink[*types.AnalyticsResult, error](&cfg.Streams.WriteSubstreamAnalytics, streams.invokeAnalyticsSubstream); err != nil {
		return err
	}
	return err
}

// build binds result producers only after every stream has been constructed.
func (streams *serviceStreams) build() error {

	if err := streams.consumeOrderProcessed.SetSource(streams.countOrderProcessed); err != nil {
		return err
	}

	if err := streams.analyzeAnalyticsSubstream.SetSource(streams.buildSubstreamAnalyticsResult); err != nil {
		return err
	}

	return nil
}

// finish links cycles after endpoint consumers have been installed.
func (streams *serviceStreams) finish() error {
	var err error

	if err = streams.cycleAnalyticsLink.SetSource(streams.continueCycleAnalytics); err != nil {
		return err
	}
	return err
}
