// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"fmt"
	"github.com/gorundebug/servicelib/runtime"

	types "github.com/gorundebug/analyticsservice/internal/types"
)

// AnalyzeAnalyticsSubstream returns a callable service-local graph.
// The handle can be injected by a custom maker before streams are initialized.
func (s *Service) AnalyzeAnalyticsSubstream() runtime.SubStream[*types.AnalyticsEvent, *types.AnalyticsResult] {
	return analyzeAnalyticsSubstreamSubStreamHandle{service: s}
}

type analyzeAnalyticsSubstreamSubStreamHandle struct {
	service *Service
}

func (h analyzeAnalyticsSubstreamSubStreamHandle) Consume(
	ctx context.Context,
	value *types.AnalyticsEvent,
	collector runtime.SubStreamCollector[*types.AnalyticsResult],
) error {
	stream := h.service.streams.analyzeAnalyticsSubstream
	if stream == nil {
		return fmt.Errorf("SubStream %s is not initialized", "Analyze Analytics Substream")
	}
	return stream.Consume(ctx, value, collector)
}
