# Code generated by servicegen. DO NOT EDIT.

GO_SERVICES := analyticsservice automationservice inventoryservice orderservice
BUF_VERSION := v1.47.2
BUF := $(TOOLS_DIR)/buf
PROTOC_VERSION := v29.3
PROTOC := $(TOOLS_DIR)/protoc
PROTOC_GEN_GO_VERSION := v1.36.3
PROTOC_GEN_GO := $(TOOLS_DIR)/protoc-gen-go
PROTOC_GEN_GO_GRPC_VERSION := v1.5.1
PROTOC_GEN_GO_GRPC := $(TOOLS_DIR)/protoc-gen-go-grpc
GOLANGCI_LINT_VERSION := v2.12.2
GOLANGCI_LINT := $(TOOLS_DIR)/golangci-lint
WORKFLOWCHECK_VERSION := v0.5.0
WORKFLOWCHECK := $(TOOLS_DIR)/workflowcheck
OAPI_CODEGEN_VERSION := v2.4.1
OAPI_CODEGEN := $(TOOLS_DIR)/oapi-codegen

LANG_BUILD_TARGETS += golang-build
LANG_TEST_TARGETS += golang-test
LANG_LINT_TARGETS += golang-lint
LANG_LINT_TARGETS += golang-workflowcheck
LANG_LINT_FIX_TARGETS += golang-lint-fix
LANG_FMT_TARGETS += golang-fmt
LANG_GEN_TARGETS += golang-gen
LANG_CLEAN_TARGETS += golang-clean
LANG_TOOL_TARGETS += golang-tools
LANG_HOST_PREP_TARGETS += golang-gen golang-codegen golang-tools
LANG_DOCKER_BUILD_TARGETS += golang-docker-build
LANG_DOCKER_DEV_BUILD_TARGETS += golang-docker-dev-build

.PHONY: golang-build golang-test golang-lint golang-lint-fix golang-fmt \
	golang-fmt-go golang-fmt-proto golang-gen golang-codegen golang-gen-proto \
	golang-gen-openapi golang-clean golang-tools \
	golang-docker-build golang-docker-dev-build go-mod-tidy go-mod-sync fmt-go fmt-proto gen-proto golang-workflowcheck \
	gen-openapi

golang-build: golang-gen ## Generate transport code and build all Go services
	@$(MAKE) -C ./analyticsservice -f Makefile service_build USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)" PROJECT_DIR="$(PROJECT_DIR)" BIN_DIR="$(BIN_DIR)"
	@$(MAKE) -C ./automationservice -f Makefile service_build USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)" PROJECT_DIR="$(PROJECT_DIR)" BIN_DIR="$(BIN_DIR)"
	@$(MAKE) -C ./inventoryservice -f Makefile service_build USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)" PROJECT_DIR="$(PROJECT_DIR)" BIN_DIR="$(BIN_DIR)"
	@$(MAKE) -C ./orderservice -f Makefile service_build USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)" PROJECT_DIR="$(PROJECT_DIR)" BIN_DIR="$(BIN_DIR)"

golang-test: golang-codegen ## Generate transport code and run tests for all Go services
	@$(MAKE) -C ./analyticsservice -f Makefile test USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)"
	@$(MAKE) -C ./automationservice -f Makefile test USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)"
	@$(MAKE) -C ./inventoryservice -f Makefile test USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)"
	@$(MAKE) -C ./orderservice -f Makefile test USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)"

golang-lint: $(GOLANGCI_LINT) ## Run Go linters
	@$(MAKE) -C ./analyticsservice -f Makefile lint GOLANGCI_LINT="$(GOLANGCI_LINT)"
	@$(MAKE) -C ./automationservice -f Makefile lint GOLANGCI_LINT="$(GOLANGCI_LINT)"
	@$(MAKE) -C ./inventoryservice -f Makefile lint GOLANGCI_LINT="$(GOLANGCI_LINT)"
	@$(MAKE) -C ./orderservice -f Makefile lint GOLANGCI_LINT="$(GOLANGCI_LINT)"

golang-lint-fix: $(GOLANGCI_LINT) ## Auto-fix Go lint issues
	@$(MAKE) -C ./analyticsservice -f Makefile lint-fix GOLANGCI_LINT="$(GOLANGCI_LINT)"
	@$(MAKE) -C ./automationservice -f Makefile lint-fix GOLANGCI_LINT="$(GOLANGCI_LINT)"
	@$(MAKE) -C ./inventoryservice -f Makefile lint-fix GOLANGCI_LINT="$(GOLANGCI_LINT)"
	@$(MAKE) -C ./orderservice -f Makefile lint-fix GOLANGCI_LINT="$(GOLANGCI_LINT)"
golang-workflowcheck: $(WORKFLOWCHECK) ## Check Go Temporal Workflow determinism
	@cd ./automationservice && GOWORK=off "$(WORKFLOWCHECK)" -config workflowcheck.generated.yaml ./...

golang-fmt-go: ## Format Go code
	@gofmt -w ./analyticsservice
	@gofmt -w ./automationservice
	@gofmt -w ./inventoryservice
	@gofmt -w ./orderservice
	@gofmt -w ./inventory_service_api
	@gofmt -w ./model_go
	@gofmt -w ./order_service_api

golang-fmt-proto: $(BUF) ## Format protobuf files used by Go
	@$(MAKE) -C ./analyticsservice -f Makefile fmt-proto TOOLS_DIR="$(TOOLS_DIR)"
	@$(MAKE) -C ./automationservice -f Makefile fmt-proto TOOLS_DIR="$(TOOLS_DIR)"
	@$(MAKE) -C ./inventoryservice -f Makefile fmt-proto TOOLS_DIR="$(TOOLS_DIR)"
	@$(MAKE) -C ./orderservice -f Makefile fmt-proto TOOLS_DIR="$(TOOLS_DIR)"
	@$(MAKE) -C ./inventory_service_api -f make.generated.mk fmt-proto TOOLS_DIR="$(TOOLS_DIR)"
	@$(MAKE) -C ./model_go -f make.generated.mk fmt-proto TOOLS_DIR="$(TOOLS_DIR)"
	@$(MAKE) -C ./order_service_api -f make.generated.mk fmt-proto TOOLS_DIR="$(TOOLS_DIR)"

golang-fmt: golang-fmt-go golang-fmt-proto ## Format all Go-owned sources

golang-gen-proto: $(PROTOC) $(PROTOC_GEN_GO) $(PROTOC_GEN_GO_GRPC) ## Generate Go protobuf code
	@$(MAKE) -C ./analyticsservice -f Makefile gen-proto PROTOC="$(PROTOC)"
	@$(MAKE) -C ./automationservice -f Makefile gen-proto PROTOC="$(PROTOC)"
	@$(MAKE) -C ./inventoryservice -f Makefile gen-proto PROTOC="$(PROTOC)"
	@$(MAKE) -C ./orderservice -f Makefile gen-proto PROTOC="$(PROTOC)"
	@$(MAKE) -C ./inventory_service_api -f make.generated.mk gen-proto PROTOC="$(PROTOC)"
	@$(MAKE) -C ./model_go -f make.generated.mk gen-proto PROTOC="$(PROTOC)"
	@$(MAKE) -C ./order_service_api -f make.generated.mk gen-proto PROTOC="$(PROTOC)"
golang-gen-openapi: $(OAPI_CODEGEN) ## Generate Go OpenAPI code
	@$(MAKE) -C ./order_service_api -f Makefile gen-openapi TOOLS_DIR="$(TOOLS_DIR)"
golang-codegen: golang-gen-proto golang-gen-openapi golang-fmt ## Generate all Go transport code without changing module manifests

golang-gen: golang-codegen ## Generate transport code without changing module manifests

golang-clean: ## Remove Go build artifacts
	@$(MAKE) -C ./analyticsservice -f Makefile clean PROJECT_DIR="$(PROJECT_DIR)" BIN_DIR="$(BIN_DIR)"
	@$(MAKE) -C ./automationservice -f Makefile clean PROJECT_DIR="$(PROJECT_DIR)" BIN_DIR="$(BIN_DIR)"
	@$(MAKE) -C ./inventoryservice -f Makefile clean PROJECT_DIR="$(PROJECT_DIR)" BIN_DIR="$(BIN_DIR)"
	@$(MAKE) -C ./orderservice -f Makefile clean PROJECT_DIR="$(PROJECT_DIR)" BIN_DIR="$(BIN_DIR)"
	@rm -rf "$(BIN_DIR)"

golang-docker-build: golang-codegen ## Build Go service Docker images entirely in Docker
	@$(MAKE) -C ./analyticsservice -f Makefile docker-build USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)"
	@$(MAKE) -C ./automationservice -f Makefile docker-build USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)"
	@$(MAKE) -C ./inventoryservice -f Makefile docker-build USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)"
	@$(MAKE) -C ./orderservice -f Makefile docker-build USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)"

golang-docker-dev-build: golang-codegen ## Build source-mounted Go development images
	@$(MAKE) -C ./analyticsservice -f Makefile docker-build-dev USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)"
	@$(MAKE) -C ./automationservice -f Makefile docker-build-dev USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)"
	@$(MAKE) -C ./inventoryservice -f Makefile docker-build-dev USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)"
	@$(MAKE) -C ./orderservice -f Makefile docker-build-dev USE_LOCAL_MODULES="$(USE_LOCAL_MODULES)"

fmt-go: golang-fmt-go ## Format Go code

fmt-proto: golang-fmt-proto ## Format protobuf files

gen-proto: golang-gen-proto ## Generate Go protobuf code
gen-openapi: golang-gen-openapi ## Generate Go OpenAPI code
go-mod-tidy: ## Run go mod tidy for all Go modules
	@cd ./analyticsservice && GOPRIVATE="$(GOPRIVATE)" go mod tidy -e
	@cd ./automationservice && GOPRIVATE="$(GOPRIVATE)" go mod tidy -e
	@cd ./inventoryservice && GOPRIVATE="$(GOPRIVATE)" go mod tidy -e
	@cd ./orderservice && GOPRIVATE="$(GOPRIVATE)" go mod tidy -e
	@cd ./inventory_service_api && GOPRIVATE="$(GOPRIVATE)" go mod tidy -e
	@cd ./model_go && GOPRIVATE="$(GOPRIVATE)" go mod tidy -e
	@cd ./order_service_api && GOPRIVATE="$(GOPRIVATE)" go mod tidy -e
	@go work use

go-mod-sync: ## Sync Go modules with published versions after git-push
	@cd ./inventory_service_api && GOWORK=off GOPRIVATE="$(GOPRIVATE)" go mod tidy -e
	@cd ./model_go && GOWORK=off GOPRIVATE="$(GOPRIVATE)" go mod tidy -e
	@cd ./order_service_api && GOWORK=off GOPRIVATE="$(GOPRIVATE)" go mod tidy -e
	@cd ./analyticsservice && GOWORK=off GOPRIVATE="$(GOPRIVATE)" go mod tidy -e
	@cd ./automationservice && GOWORK=off GOPRIVATE="$(GOPRIVATE)" go mod tidy -e
	@cd ./inventoryservice && GOWORK=off GOPRIVATE="$(GOPRIVATE)" go mod tidy -e
	@cd ./orderservice && GOWORK=off GOPRIVATE="$(GOPRIVATE)" go mod tidy -e

$(BUF):
	@mkdir -p "$(TOOLS_DIR)"
	@echo "Downloading buf $(BUF_VERSION)..."
	@set -eu; \
	tmp=$$(mktemp "$(TOOLS_DIR)/.buf.XXXXXX"); \
	trap 'rm -f "$$tmp"' EXIT INT TERM; \
	curl --fail --location --silent --show-error --connect-timeout 15 --speed-limit 1024 --speed-time 60 --retry 8 --retry-delay 2 --retry-max-time 600 --retry-all-errors \
	  "$(DEPENDENCY_GITHUB_RAW_URL)/bufbuild/buf/releases/download/$(BUF_VERSION)/buf-$(OS)-$(ARCH)" \
	  --output "$$tmp"; \
	chmod +x "$$tmp"; \
	mv "$$tmp" "$(BUF)"; \
	trap - EXIT INT TERM

$(PROTOC):
	@mkdir -p "$(TOOLS_DIR)"
	@echo "Downloading protoc $(PROTOC_VERSION)..."
	@set -eu; \
	tmp=$$(mktemp -d); \
	trap 'rm -rf "$$tmp"' EXIT INT TERM; \
	_os=$$(uname -s | sed 's/Darwin/osx/;s/Linux/linux/'); \
	_arch=$$(uname -m | sed 's/arm64/aarch_64/;s/aarch64/aarch_64/'); \
	_ver=$$(echo "$(PROTOC_VERSION)" | sed 's/v//'); \
	curl --fail --location --silent --show-error --connect-timeout 15 --speed-limit 1024 --speed-time 60 --retry 8 --retry-delay 2 --retry-max-time 600 --retry-all-errors \
	  "$(DEPENDENCY_GITHUB_RAW_URL)/protocolbuffers/protobuf/releases/download/$(PROTOC_VERSION)/protoc-$${_ver}-$${_os}-$${_arch}.zip" \
	  --output "$$tmp/protoc.zip"; \
	unzip -q "$$tmp/protoc.zip" bin/protoc -d "$$tmp/extract"; \
	chmod +x "$$tmp/extract/bin/protoc"; \
	mv "$$tmp/extract/bin/protoc" "$(PROTOC)"; \
	trap - EXIT INT TERM; \
	rm -rf "$$tmp"

$(PROTOC_GEN_GO):
	@mkdir -p "$(TOOLS_DIR)"
	@GOBIN="$(TOOLS_DIR)" go install google.golang.org/protobuf/cmd/protoc-gen-go@$(PROTOC_GEN_GO_VERSION)

$(PROTOC_GEN_GO_GRPC):
	@mkdir -p "$(TOOLS_DIR)"
	@GOBIN="$(TOOLS_DIR)" go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@$(PROTOC_GEN_GO_GRPC_VERSION)

$(GOLANGCI_LINT):
	@mkdir -p "$(TOOLS_DIR)"
	@GOBIN="$(TOOLS_DIR)" go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$(GOLANGCI_LINT_VERSION)
$(WORKFLOWCHECK):
	@mkdir -p "$(TOOLS_DIR)"
	@GOBIN="$(TOOLS_DIR)" go install go.temporal.io/sdk/contrib/tools/workflowcheck@$(WORKFLOWCHECK_VERSION)
$(OAPI_CODEGEN):
	@mkdir -p "$(TOOLS_DIR)"
	@GOBIN="$(TOOLS_DIR)" go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@$(OAPI_CODEGEN_VERSION)
golang-tools: $(BUF) $(PROTOC) $(PROTOC_GEN_GO) $(PROTOC_GEN_GO_GRPC) $(GOLANGCI_LINT) $(WORKFLOWCHECK) $(OAPI_CODEGEN) ## Install Go code-generation and lint tools