// Code generated by servicegen. DO NOT EDIT.
package config

import (
	"fmt"
	"os"
	"strconv"

	"github.com/gorundebug/servicelib/api"
	cfg "github.com/gorundebug/servicelib/runtime/config"
)

var _ = api.DataTypeAny

// Service IDs
const (
	analyticsServiceServiceID = iota + 1
)

// Stream IDs
const (
	analyticsOrdersStreamID = iota + 1
	analyticsPaymentsStreamID
	analyticsScheduleStreamID
	analyticsShipmentsStreamID
	consumeOrderProcessedStreamID
	countOrderProcessedStreamID
	highValueAnalyticsStreamID
	joinOrderPaymentAnalyticsStreamID
	keyOrdersForJoinStreamID
	keyOrdersForMultiJoinStreamID
	keyPaymentsForJoinStreamID
	keyPaymentsForMultiJoinStreamID
	keyShipmentsForMultiJoinStreamID
	multiJoinAnalyticsEventsStreamID
	routeAnalyticsResultStreamID
	splitAnalyticsOrdersStreamID
	splitAnalyticsPaymentsStreamID
	standardAnalyticsStreamID
	writeHighValueAnalyticsStreamID
	writeJoinedAnalyticsStreamID
	writeStandardAnalyticsStreamID
)

// Endpoint IDs
const (
	analyticsOrdersEndpointID = iota + 1
	analyticsPaymentsEndpointID
	analyticsScheduleEndpointID
	analyticsShipmentsEndpointID
	highValueAnalyticsEndpointID
	joinedAnalyticsEndpointID
	orderProcessedEndpointID
	standardAnalyticsEndpointID
)

// Connector IDs
const (
	analyticsFunctionsConnectorID = iota + 1
	localCronConnectorID
	orderEventsConnectorID
)

type Config struct {
	Services struct {
		AnalyticsService cfg.ServiceConfig `yaml:"analyticsService" mapstructure:"analyticsService"`
	} `yaml:"services" mapstructure:"services"`

	Streams struct {
		AnalyticsOrders           cfg.InputStreamConfig     `yaml:"analyticsOrders" mapstructure:"analyticsOrders"`
		AnalyticsPayments         cfg.InputStreamConfig     `yaml:"analyticsPayments" mapstructure:"analyticsPayments"`
		AnalyticsSchedule         cfg.InputStreamConfig     `yaml:"analyticsSchedule" mapstructure:"analyticsSchedule"`
		AnalyticsShipments        cfg.InputStreamConfig     `yaml:"analyticsShipments" mapstructure:"analyticsShipments"`
		ConsumeOrderProcessed     cfg.InputStreamConfig     `yaml:"consumeOrderProcessed" mapstructure:"consumeOrderProcessed"`
		CountOrderProcessed       cfg.ProcessStreamConfig   `yaml:"countOrderProcessed" mapstructure:"countOrderProcessed"`
		HighValueAnalytics        cfg.WhenStreamConfig      `yaml:"highValueAnalytics" mapstructure:"highValueAnalytics"`
		JoinOrderPaymentAnalytics cfg.JoinStreamConfig      `yaml:"joinOrderPaymentAnalytics" mapstructure:"joinOrderPaymentAnalytics"`
		KeyOrdersForJoin          cfg.KeyByStreamConfig     `yaml:"keyOrdersForJoin" mapstructure:"keyOrdersForJoin"`
		KeyOrdersForMultiJoin     cfg.KeyByStreamConfig     `yaml:"keyOrdersForMultiJoin" mapstructure:"keyOrdersForMultiJoin"`
		KeyPaymentsForJoin        cfg.KeyByStreamConfig     `yaml:"keyPaymentsForJoin" mapstructure:"keyPaymentsForJoin"`
		KeyPaymentsForMultiJoin   cfg.KeyByStreamConfig     `yaml:"keyPaymentsForMultiJoin" mapstructure:"keyPaymentsForMultiJoin"`
		KeyShipmentsForMultiJoin  cfg.KeyByStreamConfig     `yaml:"keyShipmentsForMultiJoin" mapstructure:"keyShipmentsForMultiJoin"`
		MultiJoinAnalyticsEvents  cfg.MultiJoinStreamConfig `yaml:"multiJoinAnalyticsEvents" mapstructure:"multiJoinAnalyticsEvents"`
		RouteAnalyticsResult      cfg.CaseStreamConfig      `yaml:"routeAnalyticsResult" mapstructure:"routeAnalyticsResult"`
		SplitAnalyticsOrders      cfg.SplitStreamConfig     `yaml:"splitAnalyticsOrders" mapstructure:"splitAnalyticsOrders"`
		SplitAnalyticsPayments    cfg.SplitStreamConfig     `yaml:"splitAnalyticsPayments" mapstructure:"splitAnalyticsPayments"`
		StandardAnalytics         cfg.WhenStreamConfig      `yaml:"standardAnalytics" mapstructure:"standardAnalytics"`
		WriteHighValueAnalytics   cfg.SinkStreamConfig      `yaml:"writeHighValueAnalytics" mapstructure:"writeHighValueAnalytics"`
		WriteJoinedAnalytics      cfg.SinkStreamConfig      `yaml:"writeJoinedAnalytics" mapstructure:"writeJoinedAnalytics"`
		WriteStandardAnalytics    cfg.SinkStreamConfig      `yaml:"writeStandardAnalytics" mapstructure:"writeStandardAnalytics"`
	} `yaml:"streams" mapstructure:"streams"`

	DataConnectors struct {
		AnalyticsFunctions cfg.CustomDataConnectorConfig `yaml:"analyticsFunctions" mapstructure:"analyticsFunctions"`
		LocalCron          cfg.CronDataConnectorConfig   `yaml:"localCron" mapstructure:"localCron"`
		OrderEvents        cfg.KafkaDataConnectorConfig  `yaml:"orderEvents" mapstructure:"orderEvents"`
	} `yaml:"dataConnectors" mapstructure:"dataConnectors"`

	Endpoints struct {
		AnalyticsOrders cfg.CustomEndpointConfig `yaml:"analyticsOrders" mapstructure:"analyticsOrders"`

		AnalyticsPayments cfg.CustomEndpointConfig `yaml:"analyticsPayments" mapstructure:"analyticsPayments"`

		AnalyticsSchedule cfg.CronEndpointConfig `yaml:"analyticsSchedule" mapstructure:"analyticsSchedule"`

		AnalyticsShipments cfg.CustomEndpointConfig `yaml:"analyticsShipments" mapstructure:"analyticsShipments"`

		HighValueAnalytics cfg.CustomEndpointConfig `yaml:"highValueAnalytics" mapstructure:"highValueAnalytics"`

		JoinedAnalytics cfg.CustomEndpointConfig `yaml:"joinedAnalytics" mapstructure:"joinedAnalytics"`

		OrderProcessed cfg.KafkaEndpointConfig `yaml:"orderProcessed" mapstructure:"orderProcessed"`

		StandardAnalytics cfg.CustomEndpointConfig `yaml:"standardAnalytics" mapstructure:"standardAnalytics"`
	} `yaml:"endpoints" mapstructure:"endpoints"`

	Pools struct {
	} `yaml:"pools" mapstructure:"pools"`

	Links struct {
	} `yaml:"links" mapstructure:"links"`

	Modules struct {
		InventoryServiceApi cfg.ModuleConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
		Model               cfg.ModuleConfig `yaml:"model" mapstructure:"model"`
		OrderServiceApi     cfg.ModuleConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
	} `yaml:"modules" mapstructure:"modules"`

	Types struct {
		AnalyticsEvent  cfg.TypeConfig `yaml:"analyticsEvent" mapstructure:"analyticsEvent"`
		AnalyticsKey    cfg.TypeConfig `yaml:"analyticsKey" mapstructure:"analyticsKey"`
		AnalyticsResult cfg.TypeConfig `yaml:"analyticsResult" mapstructure:"analyticsResult"`
		AutomationJob   cfg.TypeConfig `yaml:"automationJob" mapstructure:"automationJob"`
		OrderProcessed  cfg.TypeConfig `yaml:"orderProcessed" mapstructure:"orderProcessed"`
	} `yaml:"types" mapstructure:"types"`

	Custom     CustomConfig           `yaml:",inline" mapstructure:",squash"`
	Properties map[string]interface{} `yaml:",inline" mapstructure:",remain"`
}

func (c *Config) GetProperty(name string) interface{} {
	return c.Properties[name]
}

func (c *Config) GetServices() []*cfg.ServiceConfig {
	return []*cfg.ServiceConfig{
		&c.Services.AnalyticsService,
	}
}

func (c *Config) GetStreams() []cfg.StreamConfig {
	return []cfg.StreamConfig{
		&c.Streams.AnalyticsOrders,
		&c.Streams.AnalyticsPayments,
		&c.Streams.AnalyticsSchedule,
		&c.Streams.AnalyticsShipments,
		&c.Streams.ConsumeOrderProcessed,
		&c.Streams.CountOrderProcessed,
		&c.Streams.HighValueAnalytics,
		&c.Streams.JoinOrderPaymentAnalytics,
		&c.Streams.KeyOrdersForJoin,
		&c.Streams.KeyOrdersForMultiJoin,
		&c.Streams.KeyPaymentsForJoin,
		&c.Streams.KeyPaymentsForMultiJoin,
		&c.Streams.KeyShipmentsForMultiJoin,
		&c.Streams.MultiJoinAnalyticsEvents,
		&c.Streams.RouteAnalyticsResult,
		&c.Streams.SplitAnalyticsOrders,
		&c.Streams.SplitAnalyticsPayments,
		&c.Streams.StandardAnalytics,
		&c.Streams.WriteHighValueAnalytics,
		&c.Streams.WriteJoinedAnalytics,
		&c.Streams.WriteStandardAnalytics,
	}
}

func (c *Config) GetDataConnectors() []cfg.DataConnectorConfig {
	return []cfg.DataConnectorConfig{
		&c.DataConnectors.AnalyticsFunctions,
		&c.DataConnectors.LocalCron,
		&c.DataConnectors.OrderEvents,
	}
}

func (c *Config) GetEndpoints() []cfg.EndpointConfig {
	return []cfg.EndpointConfig{
		&c.Endpoints.AnalyticsOrders,
		&c.Endpoints.AnalyticsPayments,
		&c.Endpoints.AnalyticsSchedule,
		&c.Endpoints.AnalyticsShipments,
		&c.Endpoints.HighValueAnalytics,
		&c.Endpoints.JoinedAnalytics,
		&c.Endpoints.OrderProcessed,
		&c.Endpoints.StandardAnalytics,
	}
}

func (c *Config) GetPools() []*cfg.PoolConfig {
	return []*cfg.PoolConfig{}
}

func (c *Config) GetLinks() []*cfg.LinkConfig {
	return []*cfg.LinkConfig{}
}

func (c *Config) GetModules() []*cfg.ModuleConfig {
	return []*cfg.ModuleConfig{
		&c.Modules.InventoryServiceApi,
		&c.Modules.Model,
		&c.Modules.OrderServiceApi,
	}
}

func (c *Config) GetTypes() []*cfg.TypeConfig {
	return []*cfg.TypeConfig{
		&c.Types.AnalyticsEvent,
		&c.Types.AnalyticsKey,
		&c.Types.AnalyticsResult,
		&c.Types.AutomationJob,
		&c.Types.OrderProcessed,
	}
}

func (c *Config) ApplyEnvironment() error {
	if err := c.applyAnalyticsScheduleEnabled(); err != nil {
		return err
	}
	if err := c.applyAnalyticsScheduleMissedRunPolicy(); err != nil {
		return err
	}
	if err := c.applyAnalyticsScheduleOverlapPolicy(); err != nil {
		return err
	}
	if err := c.applyAnalyticsScheduleSchedule(); err != nil {
		return err
	}
	if err := c.applyAnalyticsScheduleTimezone(); err != nil {
		return err
	}
	if err := c.applyAnalyticsScheduleTracingEnabled(); err != nil {
		return err
	}
	if err := c.applyAnalyticsServiceDefaultGrpcTimeout(); err != nil {
		return err
	}
	if err := c.applyAnalyticsServiceEnvironment(); err != nil {
		return err
	}
	if err := c.applyAnalyticsServiceGrpcHost(); err != nil {
		return err
	}
	if err := c.applyAnalyticsServiceGrpcPort(); err != nil {
		return err
	}
	if err := c.applyAnalyticsServiceHttpHost(); err != nil {
		return err
	}
	if err := c.applyAnalyticsServiceHttpPort(); err != nil {
		return err
	}
	if err := c.applyOrderEventsBrokers(); err != nil {
		return err
	}
	if err := c.applyOrderEventsPassword(); err != nil {
		return err
	}
	if err := c.applyOrderEventsSaslMechanism(); err != nil {
		return err
	}
	if err := c.applyOrderEventsSecurityProtocol(); err != nil {
		return err
	}
	if err := c.applyOrderEventsUsername(); err != nil {
		return err
	}
	if err := c.applyOrderProcessedEnabled(); err != nil {
		return err
	}
	return nil
}

func (c *Config) applyAnalyticsScheduleEnabled() error {
	value, exists := os.LookupEnv("ANALYTICS_SCHEDULE_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert ANALYTICS_SCHEDULE_ENABLED to bool: %w", err)
	}
	c.Endpoints.AnalyticsSchedule.Enabled = boolVal

	return nil
}

func (c *Config) applyAnalyticsScheduleMissedRunPolicy() error {
	value, exists := os.LookupEnv("ANALYTICS_SCHEDULE_MISSED_RUN_POLICY")
	if !exists {
		return nil
	}

	c.Endpoints.AnalyticsSchedule.MissedRunPolicy = api.ScheduleMissedRunPolicy(value)

	return nil
}

func (c *Config) applyAnalyticsScheduleOverlapPolicy() error {
	value, exists := os.LookupEnv("ANALYTICS_SCHEDULE_OVERLAP_POLICY")
	if !exists {
		return nil
	}

	c.Endpoints.AnalyticsSchedule.OverlapPolicy = api.ScheduleOverlapPolicy(value)

	return nil
}

func (c *Config) applyAnalyticsScheduleSchedule() error {
	value, exists := os.LookupEnv("ANALYTICS_SCHEDULE_SCHEDULE")
	if !exists {
		return nil
	}

	c.Endpoints.AnalyticsSchedule.Schedule = value

	return nil
}

func (c *Config) applyAnalyticsScheduleTimezone() error {
	value, exists := os.LookupEnv("ANALYTICS_SCHEDULE_TIMEZONE")
	if !exists {
		return nil
	}

	c.Endpoints.AnalyticsSchedule.Timezone = value

	return nil
}

func (c *Config) applyAnalyticsScheduleTracingEnabled() error {
	value, exists := os.LookupEnv("ANALYTICS_SCHEDULE_TRACING_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert ANALYTICS_SCHEDULE_TRACING_ENABLED to bool: %w", err)
	}
	c.Endpoints.AnalyticsSchedule.TracingEnabled = boolVal

	return nil
}

func (c *Config) applyAnalyticsServiceDefaultGrpcTimeout() error {
	value, exists := os.LookupEnv("ANALYTICS_SERVICE_DEFAULT_GRPC_TIMEOUT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert ANALYTICS_SERVICE_DEFAULT_GRPC_TIMEOUT to int: %w", err)
	}
	c.Services.AnalyticsService.DefaultGrpcTimeout = intVal

	return nil
}

func (c *Config) applyAnalyticsServiceEnvironment() error {
	value, exists := os.LookupEnv("ANALYTICS_SERVICE_ENVIRONMENT")
	if !exists {
		return nil
	}

	c.Services.AnalyticsService.Environment = api.Environment(value)

	return nil
}

func (c *Config) applyAnalyticsServiceGrpcHost() error {
	value, exists := os.LookupEnv("ANALYTICS_SERVICE_GRPC_HOST")
	if !exists {
		return nil
	}

	c.Services.AnalyticsService.GrpcHost = value

	return nil
}

func (c *Config) applyAnalyticsServiceGrpcPort() error {
	value, exists := os.LookupEnv("ANALYTICS_SERVICE_GRPC_PORT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert ANALYTICS_SERVICE_GRPC_PORT to int: %w", err)
	}
	c.Services.AnalyticsService.GrpcPort = intVal

	return nil
}

func (c *Config) applyAnalyticsServiceHttpHost() error {
	value, exists := os.LookupEnv("ANALYTICS_SERVICE_HTTP_HOST")
	if !exists {
		return nil
	}

	c.Services.AnalyticsService.HttpHost = value

	return nil
}

func (c *Config) applyAnalyticsServiceHttpPort() error {
	value, exists := os.LookupEnv("ANALYTICS_SERVICE_HTTP_PORT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert ANALYTICS_SERVICE_HTTP_PORT to int: %w", err)
	}
	c.Services.AnalyticsService.HttpPort = intVal

	return nil
}

func (c *Config) applyOrderEventsBrokers() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_BROKERS")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.Brokers = value

	return nil
}

func (c *Config) applyOrderEventsPassword() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_PASSWORD")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.Password = value

	return nil
}

func (c *Config) applyOrderEventsSaslMechanism() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_SASL_MECHANISM")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.SaslMechanism = api.KafkaSaslMechanism(value)

	return nil
}

func (c *Config) applyOrderEventsSecurityProtocol() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_SECURITY_PROTOCOL")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.SecurityProtocol = api.KafkaSecurityProtocol(value)

	return nil
}

func (c *Config) applyOrderEventsUsername() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_USERNAME")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.Username = value

	return nil
}

func (c *Config) applyOrderProcessedEnabled() error {
	value, exists := os.LookupEnv("ORDER_PROCESSED_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert ORDER_PROCESSED_ENABLED to bool: %w", err)
	}
	c.Endpoints.OrderProcessed.Enabled = boolVal

	return nil
}

func MakeConfig() *Config {
	return &Config{
		Services: struct {
			AnalyticsService cfg.ServiceConfig `yaml:"analyticsService" mapstructure:"analyticsService"`
		}{
			AnalyticsService: cfg.ServiceConfig{
				ID:    analyticsServiceServiceID,
				Name:  "Analytics Service",
				Color: "#05ABF7",
				DefaultCallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
				GrpcHost:               "0.0.0.0",
				GrpcPort:               9203,
				HttpHost:               "0.0.0.0",
				HttpPort:               9093,
				MetricsHandler:         "metrics",
				StartupHandler:         "health/startup",
				ReadinessHandler:       "health/ready",
				LivenessHandler:        "health/live",
				KubernetesWorkloadType: "Deployment",
				ShutdownTimeout:        30000,
				StatusHandler:          "status",
				GolangVersion:          "1.25.4",
				ModulePath:             "github.com/gorundebug/analyticsservice",
			},
		},
		Streams: struct {
			AnalyticsOrders           cfg.InputStreamConfig     `yaml:"analyticsOrders" mapstructure:"analyticsOrders"`
			AnalyticsPayments         cfg.InputStreamConfig     `yaml:"analyticsPayments" mapstructure:"analyticsPayments"`
			AnalyticsSchedule         cfg.InputStreamConfig     `yaml:"analyticsSchedule" mapstructure:"analyticsSchedule"`
			AnalyticsShipments        cfg.InputStreamConfig     `yaml:"analyticsShipments" mapstructure:"analyticsShipments"`
			ConsumeOrderProcessed     cfg.InputStreamConfig     `yaml:"consumeOrderProcessed" mapstructure:"consumeOrderProcessed"`
			CountOrderProcessed       cfg.ProcessStreamConfig   `yaml:"countOrderProcessed" mapstructure:"countOrderProcessed"`
			HighValueAnalytics        cfg.WhenStreamConfig      `yaml:"highValueAnalytics" mapstructure:"highValueAnalytics"`
			JoinOrderPaymentAnalytics cfg.JoinStreamConfig      `yaml:"joinOrderPaymentAnalytics" mapstructure:"joinOrderPaymentAnalytics"`
			KeyOrdersForJoin          cfg.KeyByStreamConfig     `yaml:"keyOrdersForJoin" mapstructure:"keyOrdersForJoin"`
			KeyOrdersForMultiJoin     cfg.KeyByStreamConfig     `yaml:"keyOrdersForMultiJoin" mapstructure:"keyOrdersForMultiJoin"`
			KeyPaymentsForJoin        cfg.KeyByStreamConfig     `yaml:"keyPaymentsForJoin" mapstructure:"keyPaymentsForJoin"`
			KeyPaymentsForMultiJoin   cfg.KeyByStreamConfig     `yaml:"keyPaymentsForMultiJoin" mapstructure:"keyPaymentsForMultiJoin"`
			KeyShipmentsForMultiJoin  cfg.KeyByStreamConfig     `yaml:"keyShipmentsForMultiJoin" mapstructure:"keyShipmentsForMultiJoin"`
			MultiJoinAnalyticsEvents  cfg.MultiJoinStreamConfig `yaml:"multiJoinAnalyticsEvents" mapstructure:"multiJoinAnalyticsEvents"`
			RouteAnalyticsResult      cfg.CaseStreamConfig      `yaml:"routeAnalyticsResult" mapstructure:"routeAnalyticsResult"`
			SplitAnalyticsOrders      cfg.SplitStreamConfig     `yaml:"splitAnalyticsOrders" mapstructure:"splitAnalyticsOrders"`
			SplitAnalyticsPayments    cfg.SplitStreamConfig     `yaml:"splitAnalyticsPayments" mapstructure:"splitAnalyticsPayments"`
			StandardAnalytics         cfg.WhenStreamConfig      `yaml:"standardAnalytics" mapstructure:"standardAnalytics"`
			WriteHighValueAnalytics   cfg.SinkStreamConfig      `yaml:"writeHighValueAnalytics" mapstructure:"writeHighValueAnalytics"`
			WriteJoinedAnalytics      cfg.SinkStreamConfig      `yaml:"writeJoinedAnalytics" mapstructure:"writeJoinedAnalytics"`
			WriteStandardAnalytics    cfg.SinkStreamConfig      `yaml:"writeStandardAnalytics" mapstructure:"writeStandardAnalytics"`
		}{
			AnalyticsOrders: cfg.InputStreamConfig{
				ID:         analyticsOrdersStreamID,
				Name:       "Analytics Orders",
				Pipeline:   "analyticsSources",
				IdService:  analyticsServiceServiceID,
				XPos:       -1600,
				YPos:       220,
				ValueType:  "AnalyticsEvent",
				IdEndpoint: analyticsOrdersEndpointID,
			},

			AnalyticsPayments: cfg.InputStreamConfig{
				ID:         analyticsPaymentsStreamID,
				Name:       "Analytics Payments",
				Pipeline:   "analyticsSources",
				IdService:  analyticsServiceServiceID,
				XPos:       -1600,
				YPos:       430,
				ValueType:  "AnalyticsEvent",
				IdEndpoint: analyticsPaymentsEndpointID,
			},

			AnalyticsSchedule: cfg.InputStreamConfig{
				ID:         analyticsScheduleStreamID,
				Name:       "Analytics Schedule",
				Pipeline:   "analytics",
				IdService:  analyticsServiceServiceID,
				XPos:       -1600,
				YPos:       -205,
				ValueType:  "AutomationJob",
				IdEndpoint: analyticsScheduleEndpointID,
			},

			AnalyticsShipments: cfg.InputStreamConfig{
				ID:         analyticsShipmentsStreamID,
				Name:       "Analytics Shipments",
				Pipeline:   "analyticsSources",
				IdService:  analyticsServiceServiceID,
				XPos:       -1600,
				YPos:       780,
				ValueType:  "AnalyticsEvent",
				IdEndpoint: analyticsShipmentsEndpointID,
			},

			ConsumeOrderProcessed: cfg.InputStreamConfig{
				ID:         consumeOrderProcessedStreamID,
				Name:       "Consume Order Processed",
				Pipeline:   "analytics",
				IdService:  analyticsServiceServiceID,
				IdSource:   countOrderProcessedStreamID,
				XPos:       -1190,
				YPos:       -205,
				ValueType:  "OrderProcessed",
				IdEndpoint: orderProcessedEndpointID,
			},

			CountOrderProcessed: cfg.ProcessStreamConfig{
				ID:                  countOrderProcessedStreamID,
				Name:                "Count Order Processed",
				Pipeline:            "analytics",
				IdService:           analyticsServiceServiceID,
				IdSource:            consumeOrderProcessedStreamID,
				XPos:                -1390,
				YPos:                -19,
				FunctionPackage:     "analytics",
				FunctionName:        "CountOrderProcessed",
				FunctionDescription: "Count successful and unsuccessful orders independently, then return the event unchanged.\n",
			},

			HighValueAnalytics: cfg.WhenStreamConfig{
				ID:        highValueAnalyticsStreamID,
				Name:      "High Value Analytics",
				Pipeline:  "multiJoinAnalytics",
				IdService: analyticsServiceServiceID,
				IdSource:  routeAnalyticsResultStreamID,
				XPos:      -400,
				YPos:      650,
				ValueType: "AnalyticsResult",
			},

			JoinOrderPaymentAnalytics: cfg.JoinStreamConfig{
				ID:                  joinOrderPaymentAnalyticsStreamID,
				Name:                "Join Order Payment Analytics",
				Pipeline:            "joinAnalytics",
				IdService:           analyticsServiceServiceID,
				IdSource:            keyOrdersForJoinStreamID,
				IdSources:           []int{keyPaymentsForJoinStreamID},
				XPos:                -900,
				YPos:                260,
				ValueType:           "AnalyticsResult",
				JoinType:            api.JoinTypeInner,
				JoinStorage:         api.JoinStorageTypeHashMap,
				Ttl:                 60000,
				RenewTTL:            true,
				FunctionPackage:     "joinanalytics",
				FunctionName:        "JoinOrderPaymentAnalytics",
				FunctionDescription: "Join matching order and payment analytics events and emit their combined total.",
			},

			KeyOrdersForJoin: cfg.KeyByStreamConfig{
				ID:                  keyOrdersForJoinStreamID,
				Name:                "Key Orders For Join",
				Pipeline:            "joinAnalytics",
				IdService:           analyticsServiceServiceID,
				IdSource:            splitAnalyticsOrdersStreamID,
				XPos:                -1160,
				YPos:                170,
				ValueType:           "AnalyticsEvent",
				KeyType:             "AnalyticsKey",
				FunctionPackage:     "joinanalytics",
				FunctionName:        "KeyOrdersForJoin",
				FunctionDescription: "Key the order analytics event by correlation key.",
			},

			KeyOrdersForMultiJoin: cfg.KeyByStreamConfig{
				ID:                  keyOrdersForMultiJoinStreamID,
				Name:                "Key Orders For Multi Join",
				Pipeline:            "multiJoinAnalytics",
				IdService:           analyticsServiceServiceID,
				IdSource:            splitAnalyticsOrdersStreamID,
				XPos:                -1160,
				YPos:                570,
				ValueType:           "AnalyticsEvent",
				KeyType:             "AnalyticsKey",
				FunctionPackage:     "multijoinanalytics",
				FunctionName:        "KeyOrdersForMultiJoin",
				FunctionDescription: "Key the order analytics event for the multi-way join.",
			},

			KeyPaymentsForJoin: cfg.KeyByStreamConfig{
				ID:                  keyPaymentsForJoinStreamID,
				Name:                "Key Payments For Join",
				Pipeline:            "joinAnalytics",
				IdService:           analyticsServiceServiceID,
				IdSource:            splitAnalyticsPaymentsStreamID,
				XPos:                -1160,
				YPos:                350,
				ValueType:           "AnalyticsEvent",
				KeyType:             "AnalyticsKey",
				FunctionPackage:     "joinanalytics",
				FunctionName:        "KeyPaymentsForJoin",
				FunctionDescription: "Key the payment analytics event by correlation key.",
			},

			KeyPaymentsForMultiJoin: cfg.KeyByStreamConfig{
				ID:                  keyPaymentsForMultiJoinStreamID,
				Name:                "Key Payments For Multi Join",
				Pipeline:            "multiJoinAnalytics",
				IdService:           analyticsServiceServiceID,
				IdSource:            splitAnalyticsPaymentsStreamID,
				XPos:                -1160,
				YPos:                740,
				ValueType:           "AnalyticsEvent",
				KeyType:             "AnalyticsKey",
				FunctionPackage:     "multijoinanalytics",
				FunctionName:        "KeyPaymentsForMultiJoin",
				FunctionDescription: "Key the payment analytics event for the multi-way join.",
			},

			KeyShipmentsForMultiJoin: cfg.KeyByStreamConfig{
				ID:                  keyShipmentsForMultiJoinStreamID,
				Name:                "Key Shipments For Multi Join",
				Pipeline:            "multiJoinAnalytics",
				IdService:           analyticsServiceServiceID,
				IdSource:            analyticsShipmentsStreamID,
				XPos:                -1160,
				YPos:                910,
				ValueType:           "AnalyticsEvent",
				KeyType:             "AnalyticsKey",
				FunctionPackage:     "multijoinanalytics",
				FunctionName:        "KeyShipmentsForMultiJoin",
				FunctionDescription: "Key the shipment analytics event for the multi-way join.",
			},

			MultiJoinAnalyticsEvents: cfg.MultiJoinStreamConfig{
				ID:                  multiJoinAnalyticsEventsStreamID,
				Name:                "Multi Join Analytics Events",
				Pipeline:            "multiJoinAnalytics",
				IdService:           analyticsServiceServiceID,
				IdSource:            keyOrdersForMultiJoinStreamID,
				IdSources:           []int{keyPaymentsForMultiJoinStreamID, keyShipmentsForMultiJoinStreamID},
				XPos:                -900,
				YPos:                740,
				ValueType:           "AnalyticsResult",
				JoinStorage:         api.JoinStorageTypeHashMap,
				Ttl:                 60000,
				RenewTTL:            true,
				FunctionPackage:     "multijoinanalytics",
				FunctionName:        "MultiJoinAnalyticsEvents",
				FunctionDescription: "Combine matching order, payment, and shipment analytics events.",
			},

			RouteAnalyticsResult: cfg.CaseStreamConfig{
				ID:                  routeAnalyticsResultStreamID,
				Name:                "Route Analytics Result",
				Pipeline:            "multiJoinAnalytics",
				IdService:           analyticsServiceServiceID,
				IdSource:            multiJoinAnalyticsEventsStreamID,
				XPos:                -650,
				YPos:                740,
				FunctionPackage:     "multijoinanalytics",
				FunctionName:        "RouteAnalyticsResult",
				FunctionDescription: "Route high-value analytics results to the first branch and all others to the second branch.",
			},

			SplitAnalyticsOrders: cfg.SplitStreamConfig{
				ID:        splitAnalyticsOrdersStreamID,
				Name:      "Split Analytics Orders",
				Pipeline:  "analyticsSources",
				IdService: analyticsServiceServiceID,
				IdSource:  analyticsOrdersStreamID,
				XPos:      -1390,
				YPos:      220,
			},

			SplitAnalyticsPayments: cfg.SplitStreamConfig{
				ID:        splitAnalyticsPaymentsStreamID,
				Name:      "Split Analytics Payments",
				Pipeline:  "analyticsSources",
				IdService: analyticsServiceServiceID,
				IdSource:  analyticsPaymentsStreamID,
				XPos:      -1390,
				YPos:      430,
			},

			StandardAnalytics: cfg.WhenStreamConfig{
				ID:        standardAnalyticsStreamID,
				Name:      "Standard Analytics",
				Pipeline:  "multiJoinAnalytics",
				IdService: analyticsServiceServiceID,
				IdSource:  routeAnalyticsResultStreamID,
				XPos:      -400,
				YPos:      830,
				ValueType: "AnalyticsResult",
			},

			WriteHighValueAnalytics: cfg.SinkStreamConfig{
				ID:         writeHighValueAnalyticsStreamID,
				Name:       "Write High Value Analytics",
				Pipeline:   "multiJoinAnalytics",
				IdService:  analyticsServiceServiceID,
				IdSource:   highValueAnalyticsStreamID,
				XPos:       -130,
				YPos:       650,
				ValueType:  "AnalyticsResult",
				IdEndpoint: highValueAnalyticsEndpointID,
			},

			WriteJoinedAnalytics: cfg.SinkStreamConfig{
				ID:         writeJoinedAnalyticsStreamID,
				Name:       "Write Joined Analytics",
				Pipeline:   "joinAnalytics",
				IdService:  analyticsServiceServiceID,
				IdSource:   joinOrderPaymentAnalyticsStreamID,
				XPos:       -640,
				YPos:       260,
				ValueType:  "AnalyticsResult",
				IdEndpoint: joinedAnalyticsEndpointID,
			},

			WriteStandardAnalytics: cfg.SinkStreamConfig{
				ID:         writeStandardAnalyticsStreamID,
				Name:       "Write Standard Analytics",
				Pipeline:   "multiJoinAnalytics",
				IdService:  analyticsServiceServiceID,
				IdSource:   standardAnalyticsStreamID,
				XPos:       -130,
				YPos:       830,
				ValueType:  "AnalyticsResult",
				IdEndpoint: standardAnalyticsEndpointID,
			},
		},
		DataConnectors: struct {
			AnalyticsFunctions cfg.CustomDataConnectorConfig `yaml:"analyticsFunctions" mapstructure:"analyticsFunctions"`
			LocalCron          cfg.CronDataConnectorConfig   `yaml:"localCron" mapstructure:"localCron"`
			OrderEvents        cfg.KafkaDataConnectorConfig  `yaml:"orderEvents" mapstructure:"orderEvents"`
		}{
			AnalyticsFunctions: cfg.CustomDataConnectorConfig{
				ID:             analyticsFunctionsConnectorID,
				Name:           "Analytics Functions",
				Implementation: api.DataConnectorImplementationFunction,
			},

			LocalCron: cfg.CronDataConnectorConfig{
				ID:             localCronConnectorID,
				Name:           "Local Cron",
				Implementation: api.DataConnectorImplementationGoGocron,
			},

			OrderEvents: cfg.KafkaDataConnectorConfig{
				ID:               orderEventsConnectorID,
				Name:             "Order Events",
				Implementation:   api.DataConnectorImplementationIBMsarama,
				Brokers:          "redpanda:9092",
				Version:          "2.8.0",
				DialTimeout:      5000,
				SecurityProtocol: "PLAINTEXT",
				SaslMechanism:    "SCRAM-SHA-512",
			},
		},
		Endpoints: struct {
			AnalyticsOrders    cfg.CustomEndpointConfig `yaml:"analyticsOrders" mapstructure:"analyticsOrders"`
			AnalyticsPayments  cfg.CustomEndpointConfig `yaml:"analyticsPayments" mapstructure:"analyticsPayments"`
			AnalyticsSchedule  cfg.CronEndpointConfig   `yaml:"analyticsSchedule" mapstructure:"analyticsSchedule"`
			AnalyticsShipments cfg.CustomEndpointConfig `yaml:"analyticsShipments" mapstructure:"analyticsShipments"`
			HighValueAnalytics cfg.CustomEndpointConfig `yaml:"highValueAnalytics" mapstructure:"highValueAnalytics"`
			JoinedAnalytics    cfg.CustomEndpointConfig `yaml:"joinedAnalytics" mapstructure:"joinedAnalytics"`
			OrderProcessed     cfg.KafkaEndpointConfig  `yaml:"orderProcessed" mapstructure:"orderProcessed"`
			StandardAnalytics  cfg.CustomEndpointConfig `yaml:"standardAnalytics" mapstructure:"standardAnalytics"`
		}{
			AnalyticsOrders: cfg.CustomEndpointConfig{
				ID:                  analyticsOrdersEndpointID,
				Name:                "Analytics Orders",
				IdDataConnector:     analyticsFunctionsConnectorID,
				FunctionName:        "AnalyticsOrders",
				FunctionPackage:     "endpoint",
				FunctionDescription: "Produce a deterministic order analytics event for the canonical join examples.",
			},

			AnalyticsPayments: cfg.CustomEndpointConfig{
				ID:                  analyticsPaymentsEndpointID,
				Name:                "Analytics Payments",
				IdDataConnector:     analyticsFunctionsConnectorID,
				FunctionName:        "AnalyticsPayments",
				FunctionPackage:     "endpoint",
				FunctionDescription: "Produce a deterministic payment analytics event for the canonical join examples.",
			},

			AnalyticsSchedule: cfg.CronEndpointConfig{
				ID:                  analyticsScheduleEndpointID,
				Name:                "Analytics Schedule",
				IdDataConnector:     localCronConnectorID,
				Enabled:             true,
				Schedule:            "*/5 * * * *",
				Timezone:            "UTC",
				OverlapPolicy:       api.ScheduleOverlapPolicySkip,
				MissedRunPolicy:     api.ScheduleMissedRunPolicyFireOnce,
				FunctionName:        "AnalyticsSchedule",
				FunctionPackage:     "cron",
				FunctionDescription: "Create an analytics job message identifying the local scheduled firing.\n",
			},

			AnalyticsShipments: cfg.CustomEndpointConfig{
				ID:                  analyticsShipmentsEndpointID,
				Name:                "Analytics Shipments",
				IdDataConnector:     analyticsFunctionsConnectorID,
				FunctionName:        "AnalyticsShipments",
				FunctionPackage:     "endpoint",
				FunctionDescription: "Produce a deterministic shipment analytics event for the canonical multi-way join example.",
			},

			HighValueAnalytics: cfg.CustomEndpointConfig{
				ID:                  highValueAnalyticsEndpointID,
				Name:                "High Value Analytics",
				IdDataConnector:     analyticsFunctionsConnectorID,
				FunctionName:        "HighValueAnalytics",
				FunctionPackage:     "endpoint",
				FunctionDescription: "Validate and record analytics results routed to the high-value Case branch.",
			},

			JoinedAnalytics: cfg.CustomEndpointConfig{
				ID:                  joinedAnalyticsEndpointID,
				Name:                "Joined Analytics",
				IdDataConnector:     analyticsFunctionsConnectorID,
				FunctionName:        "JoinedAnalytics",
				FunctionPackage:     "endpoint",
				FunctionDescription: "Validate and record the result of the two-way analytics join.",
			},

			OrderProcessed: cfg.KafkaEndpointConfig{
				ID:                  orderProcessedEndpointID,
				Name:                "Order Processed",
				IdDataConnector:     orderEventsConnectorID,
				Enabled:             true,
				CreateTopic:         true,
				Topic:               "order-processed",
				Partitions:          1,
				ReplicationFactor:   1,
				ConsumerGroup:       "analytics-service",
				FunctionName:        "OrderProcessedEndpoint",
				FunctionPackage:     "endpoint",
				FunctionDescription: "Exchange OrderProcessed events keyed by order ID.\nProducers include the final status, processing time, total and confirmed item counts, and a failure reason for unsuccessful orders.\nConsumers decode the event and mark its Kafka message processed only after the pipeline handles it successfully.\n",
			},

			StandardAnalytics: cfg.CustomEndpointConfig{
				ID:                  standardAnalyticsEndpointID,
				Name:                "Standard Analytics",
				IdDataConnector:     analyticsFunctionsConnectorID,
				FunctionName:        "StandardAnalytics",
				FunctionPackage:     "endpoint",
				FunctionDescription: "Validate and record analytics results routed to the standard Case branch.",
			},
		},
		Pools: struct {
		}{},
		Links: struct {
		}{},
		Modules: struct {
			InventoryServiceApi cfg.ModuleConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
			Model               cfg.ModuleConfig `yaml:"model" mapstructure:"model"`
			OrderServiceApi     cfg.ModuleConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
		}{
			InventoryServiceApi: cfg.ModuleConfig{
				Name: "inventory_service_api",
				Path: "github.com/gorundebug/inventory_service_api",
			},
			Model: cfg.ModuleConfig{
				Name: "model",
				Path: "github.com/gorundebug/model_go",
			},
			OrderServiceApi: cfg.ModuleConfig{
				Name: "order_service_api",
				Path: "github.com/gorundebug/order_service_api",
			},
		},
		Types: struct {
			AnalyticsEvent  cfg.TypeConfig `yaml:"analyticsEvent" mapstructure:"analyticsEvent"`
			AnalyticsKey    cfg.TypeConfig `yaml:"analyticsKey" mapstructure:"analyticsKey"`
			AnalyticsResult cfg.TypeConfig `yaml:"analyticsResult" mapstructure:"analyticsResult"`
			AutomationJob   cfg.TypeConfig `yaml:"automationJob" mapstructure:"automationJob"`
			OrderProcessed  cfg.TypeConfig `yaml:"orderProcessed" mapstructure:"orderProcessed"`
		}{
			AnalyticsEvent: cfg.TypeConfig{
				Name:             "AnalyticsEvent",
				Type:             api.DataTypeStruct,
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},

			AnalyticsKey: cfg.TypeConfig{
				Name: "AnalyticsKey",
				Type: api.DataTypeString,
			},

			AnalyticsResult: cfg.TypeConfig{
				Name:             "AnalyticsResult",
				Type:             api.DataTypeStruct,
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},

			AutomationJob: cfg.TypeConfig{
				Name:       "AutomationJob",
				Type:       api.DataTypeString,
				Module:     "model",
				PublicType: true,
			},

			OrderProcessed: cfg.TypeConfig{
				Name:             "OrderProcessed",
				Type:             api.DataTypeStruct,
				Module:           "model",
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},
		},
	}
}
