// Code generated by servicegen. DO NOT EDIT.
package config

import (
	"fmt"
	"os"
	"strconv"

	"github.com/gorundebug/servicelib/api"
	cfg "github.com/gorundebug/servicelib/runtime/config"
)

var _ = api.DataTypeAny

// Service IDs
const (
	analyticsServiceServiceID = iota + 1
)

// Stream IDs
const (
	consumeOrderProcessedStreamID = iota + 1
	countOrderProcessedStreamID
)

// Endpoint IDs
const (
	orderProcessedEndpointID = iota + 1
)

// Connector IDs
const (
	orderEventsConnectorID = iota + 1
)

type Config struct {
	Services struct {
		AnalyticsService cfg.ServiceConfig `yaml:"analyticsService" mapstructure:"analyticsService"`
	} `yaml:"services" mapstructure:"services"`

	Streams struct {
		ConsumeOrderProcessed cfg.InputStreamConfig   `yaml:"consumeOrderProcessed" mapstructure:"consumeOrderProcessed"`
		CountOrderProcessed   cfg.ProcessStreamConfig `yaml:"countOrderProcessed" mapstructure:"countOrderProcessed"`
	} `yaml:"streams" mapstructure:"streams"`

	DataConnectors struct {
		OrderEvents cfg.KafkaDataConnectorConfig `yaml:"orderEvents" mapstructure:"orderEvents"`
	} `yaml:"dataConnectors" mapstructure:"dataConnectors"`

	Endpoints struct {
		OrderProcessed cfg.KafkaEndpointConfig `yaml:"orderProcessed" mapstructure:"orderProcessed"`
	} `yaml:"endpoints" mapstructure:"endpoints"`

	Pools struct {
	} `yaml:"pools" mapstructure:"pools"`

	Links struct {
	} `yaml:"links" mapstructure:"links"`

	Modules struct {
		InventoryServiceApi cfg.ModuleConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
		Model               cfg.ModuleConfig `yaml:"model" mapstructure:"model"`
		OrderServiceApi     cfg.ModuleConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
	} `yaml:"modules" mapstructure:"modules"`

	Types struct {
		OrderProcessed cfg.TypeConfig `yaml:"orderProcessed" mapstructure:"orderProcessed"`
	} `yaml:"types" mapstructure:"types"`

	Custom     CustomConfig           `yaml:",inline" mapstructure:",squash"`
	Properties map[string]interface{} `yaml:",inline" mapstructure:",remain"`
}

func (c *Config) GetProperty(name string) interface{} {
	return c.Properties[name]
}

func (c *Config) GetServices() []*cfg.ServiceConfig {
	return []*cfg.ServiceConfig{
		&c.Services.AnalyticsService,
	}
}

func (c *Config) GetStreams() []cfg.StreamConfig {
	return []cfg.StreamConfig{
		&c.Streams.ConsumeOrderProcessed,
		&c.Streams.CountOrderProcessed,
	}
}

func (c *Config) GetDataConnectors() []cfg.DataConnectorConfig {
	return []cfg.DataConnectorConfig{
		&c.DataConnectors.OrderEvents,
	}
}

func (c *Config) GetEndpoints() []cfg.EndpointConfig {
	return []cfg.EndpointConfig{
		&c.Endpoints.OrderProcessed,
	}
}

func (c *Config) GetPools() []*cfg.PoolConfig {
	return []*cfg.PoolConfig{}
}

func (c *Config) GetLinks() []*cfg.LinkConfig {
	return []*cfg.LinkConfig{}
}

func (c *Config) GetModules() []*cfg.ModuleConfig {
	return []*cfg.ModuleConfig{
		&c.Modules.InventoryServiceApi,
		&c.Modules.Model,
		&c.Modules.OrderServiceApi,
	}
}

func (c *Config) GetTypes() []*cfg.TypeConfig {
	return []*cfg.TypeConfig{
		&c.Types.OrderProcessed,
	}
}

func (c *Config) ApplyEnvironment() error {
	if err := c.applyAnalyticsServiceDefaultGrpcTimeout(); err != nil {
		return err
	}
	if err := c.applyAnalyticsServiceEnvironment(); err != nil {
		return err
	}
	if err := c.applyAnalyticsServiceGrpcHost(); err != nil {
		return err
	}
	if err := c.applyAnalyticsServiceGrpcPort(); err != nil {
		return err
	}
	if err := c.applyAnalyticsServiceHttpHost(); err != nil {
		return err
	}
	if err := c.applyAnalyticsServiceHttpPort(); err != nil {
		return err
	}
	if err := c.applyOrderEventsBrokers(); err != nil {
		return err
	}
	if err := c.applyOrderEventsPassword(); err != nil {
		return err
	}
	if err := c.applyOrderEventsSaslMechanism(); err != nil {
		return err
	}
	if err := c.applyOrderEventsSecurityProtocol(); err != nil {
		return err
	}
	if err := c.applyOrderEventsUsername(); err != nil {
		return err
	}
	if err := c.applyOrderProcessedEnabled(); err != nil {
		return err
	}
	return nil
}

func (c *Config) applyAnalyticsServiceDefaultGrpcTimeout() error {
	value, exists := os.LookupEnv("ANALYTICS_SERVICE_DEFAULT_GRPC_TIMEOUT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert ANALYTICS_SERVICE_DEFAULT_GRPC_TIMEOUT to int: %w", err)
	}
	c.Services.AnalyticsService.DefaultGrpcTimeout = intVal

	return nil
}

func (c *Config) applyAnalyticsServiceEnvironment() error {
	value, exists := os.LookupEnv("ANALYTICS_SERVICE_ENVIRONMENT")
	if !exists {
		return nil
	}

	c.Services.AnalyticsService.Environment = api.Environment(value)

	return nil
}

func (c *Config) applyAnalyticsServiceGrpcHost() error {
	value, exists := os.LookupEnv("ANALYTICS_SERVICE_GRPC_HOST")
	if !exists {
		return nil
	}

	c.Services.AnalyticsService.GrpcHost = value

	return nil
}

func (c *Config) applyAnalyticsServiceGrpcPort() error {
	value, exists := os.LookupEnv("ANALYTICS_SERVICE_GRPC_PORT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert ANALYTICS_SERVICE_GRPC_PORT to int: %w", err)
	}
	c.Services.AnalyticsService.GrpcPort = intVal

	return nil
}

func (c *Config) applyAnalyticsServiceHttpHost() error {
	value, exists := os.LookupEnv("ANALYTICS_SERVICE_HTTP_HOST")
	if !exists {
		return nil
	}

	c.Services.AnalyticsService.HttpHost = value

	return nil
}

func (c *Config) applyAnalyticsServiceHttpPort() error {
	value, exists := os.LookupEnv("ANALYTICS_SERVICE_HTTP_PORT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert ANALYTICS_SERVICE_HTTP_PORT to int: %w", err)
	}
	c.Services.AnalyticsService.HttpPort = intVal

	return nil
}

func (c *Config) applyOrderEventsBrokers() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_BROKERS")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.Brokers = value

	return nil
}

func (c *Config) applyOrderEventsPassword() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_PASSWORD")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.Password = value

	return nil
}

func (c *Config) applyOrderEventsSaslMechanism() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_SASL_MECHANISM")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.SaslMechanism = api.KafkaSaslMechanism(value)

	return nil
}

func (c *Config) applyOrderEventsSecurityProtocol() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_SECURITY_PROTOCOL")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.SecurityProtocol = api.KafkaSecurityProtocol(value)

	return nil
}

func (c *Config) applyOrderEventsUsername() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_USERNAME")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.Username = value

	return nil
}

func (c *Config) applyOrderProcessedEnabled() error {
	value, exists := os.LookupEnv("ORDER_PROCESSED_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert ORDER_PROCESSED_ENABLED to bool: %w", err)
	}
	c.Endpoints.OrderProcessed.Enabled = boolVal

	return nil
}

func MakeConfig() *Config {
	return &Config{
		Services: struct {
			AnalyticsService cfg.ServiceConfig `yaml:"analyticsService" mapstructure:"analyticsService"`
		}{
			AnalyticsService: cfg.ServiceConfig{
				ID:    analyticsServiceServiceID,
				Name:  "Analytics Service",
				Color: "#05ABF7",
				DefaultCallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
				GrpcHost:               "0.0.0.0",
				GrpcPort:               9203,
				HttpHost:               "0.0.0.0",
				HttpPort:               9093,
				MetricsHandler:         "metrics",
				StartupHandler:         "health/startup",
				ReadinessHandler:       "health/ready",
				LivenessHandler:        "health/live",
				KubernetesWorkloadType: "Deployment",
				ShutdownTimeout:        30000,
				StatusHandler:          "status",
				GolangVersion:          "1.25.4",
				ModulePath:             "github.com/gorundebug/analyticsservice",
			},
		},
		Streams: struct {
			ConsumeOrderProcessed cfg.InputStreamConfig   `yaml:"consumeOrderProcessed" mapstructure:"consumeOrderProcessed"`
			CountOrderProcessed   cfg.ProcessStreamConfig `yaml:"countOrderProcessed" mapstructure:"countOrderProcessed"`
		}{
			ConsumeOrderProcessed: cfg.InputStreamConfig{
				ID:         consumeOrderProcessedStreamID,
				Name:       "Consume Order Processed",
				Pipeline:   "analytics",
				IdService:  analyticsServiceServiceID,
				IdSource:   countOrderProcessedStreamID,
				XPos:       -1190,
				YPos:       -205,
				ValueType:  "OrderProcessed",
				IdEndpoint: orderProcessedEndpointID,
			},

			CountOrderProcessed: cfg.ProcessStreamConfig{
				ID:                  countOrderProcessedStreamID,
				Name:                "Count Order Processed",
				Pipeline:            "analytics",
				IdService:           analyticsServiceServiceID,
				IdSource:            consumeOrderProcessedStreamID,
				XPos:                -1390,
				YPos:                -19,
				FunctionPackage:     "analytics",
				FunctionName:        "CountOrderProcessed",
				FunctionDescription: "Count successful and unsuccessful orders independently, then return the event unchanged.\n",
			},
		},
		DataConnectors: struct {
			OrderEvents cfg.KafkaDataConnectorConfig `yaml:"orderEvents" mapstructure:"orderEvents"`
		}{
			OrderEvents: cfg.KafkaDataConnectorConfig{
				ID:               orderEventsConnectorID,
				Name:             "Order Events",
				Implementation:   api.DataConnectorImplementationIBMsarama,
				Brokers:          "redpanda:9092",
				Version:          "2.8.0",
				DialTimeout:      5000,
				SecurityProtocol: "PLAINTEXT",
				SaslMechanism:    "SCRAM-SHA-512",
			},
		},
		Endpoints: struct {
			OrderProcessed cfg.KafkaEndpointConfig `yaml:"orderProcessed" mapstructure:"orderProcessed"`
		}{
			OrderProcessed: cfg.KafkaEndpointConfig{
				ID:                  orderProcessedEndpointID,
				Name:                "Order Processed",
				IdDataConnector:     orderEventsConnectorID,
				Enabled:             true,
				CreateTopic:         true,
				Topic:               "order-processed",
				Partitions:          1,
				ReplicationFactor:   1,
				ConsumerGroup:       "analytics-service",
				FunctionName:        "OrderProcessedEndpoint",
				FunctionPackage:     "endpoint",
				FunctionDescription: "Exchange OrderProcessed events keyed by order ID.\nProducers include the final status, processing time, total and confirmed item counts, and a failure reason for unsuccessful orders.\nConsumers decode the event and mark its Kafka message processed only after the pipeline handles it successfully.\n",
			},
		},
		Pools: struct {
		}{},
		Links: struct {
		}{},
		Modules: struct {
			InventoryServiceApi cfg.ModuleConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
			Model               cfg.ModuleConfig `yaml:"model" mapstructure:"model"`
			OrderServiceApi     cfg.ModuleConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
		}{
			InventoryServiceApi: cfg.ModuleConfig{
				Name: "inventory_service_api",
				Path: "github.com/gorundebug/inventory_service_api",
			},
			Model: cfg.ModuleConfig{
				Name: "model",
				Path: "github.com/gorundebug/model",
			},
			OrderServiceApi: cfg.ModuleConfig{
				Name: "order_service_api",
				Path: "github.com/gorundebug/order_service_api",
			},
		},
		Types: struct {
			OrderProcessed cfg.TypeConfig `yaml:"orderProcessed" mapstructure:"orderProcessed"`
		}{
			OrderProcessed: cfg.TypeConfig{
				Name:             "OrderProcessed",
				Type:             api.DataTypeStruct,
				Module:           "model",
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},
		},
	}
}
